import type { CompositionValues, IngredientProfile, RecipeDraft } from "./types"

function solids(values: Partial<CompositionValues>): CompositionValues {
  return {
    fat: values.fat ?? 0,
    protein: values.protein ?? 0,
    sugars: values.sugars ?? 0,
    starch: values.starch ?? 0,
    fiber: values.fiber ?? 0,
    salt: values.salt ?? 0,
    other: values.other ?? 0,
  }
}

export const INGREDIENT_PROFILES: IngredientProfile[] = [
  {
    key: "bread-flour",
    name: "Bread flour",
    aliases: ["strong flour", "strong bread flour", "white bread flour"],
    role: "flour",
    water: 12.7,
    solids: solids({
      fat: 1.5,
      protein: 12,
      sugars: 0.3,
      starch: 69.8,
      fiber: 2.7,
      other: 1,
    }),
  },
  {
    key: "all-purpose-flour",
    name: "Flour",
    aliases: [
      "all purpose flour",
      "plain flour",
      "stoneground plain flour",
      "ap flour",
    ],
    role: "flour",
    water: 11.9,
    solids: solids({
      fat: 1,
      protein: 10.3,
      sugars: 0.3,
      starch: 72.8,
      fiber: 2.7,
      other: 1,
    }),
  },
  {
    key: "hazelnut-flour",
    name: "Hazelnut flour",
    aliases: ["ground hazelnuts", "hazelnut meal"],
    role: "flour",
    water: 4.8,
    solids: solids({
      fat: 60.8,
      protein: 15,
      sugars: 4.3,
      starch: 3.5,
      fiber: 9.7,
      other: 1.9,
    }),
  },
  {
    key: "whole-wheat-flour",
    name: "Whole wheat flour",
    aliases: ["wholemeal flour", "whole grain flour"],
    role: "flour",
    water: 10.7,
    solids: solids({
      fat: 2.5,
      protein: 13.2,
      sugars: 0.4,
      starch: 61.8,
      fiber: 10.7,
      other: 0.7,
    }),
  },
  {
    key: "water",
    name: "Water",
    aliases: ["warm water", "cold water", "filtered water"],
    role: "hydration",
    water: 100,
    solids: solids({}),
  },
  {
    key: "whole-milk",
    name: "Whole milk",
    aliases: ["full fat milk", "full-fat milk"],
    role: "hydration",
    water: 88.1,
    solids: solids({
      fat: 3.25,
      protein: 3.2,
      sugars: 4.8,
      salt: 0.1,
      other: 0.55,
    }),
  },
  {
    key: "olive-oil",
    name: "Olive oil",
    aliases: ["extra virgin olive oil", "evoo"],
    role: "fat",
    water: 0.2,
    solids: solids({ fat: 99.8 }),
  },
  {
    key: "unsalted-butter",
    name: "Unsalted butter",
    aliases: ["butter unsalted", "butter"],
    role: "fat",
    water: 16,
    solids: solids({
      fat: 81.1,
      protein: 0.9,
      sugars: 0.1,
      salt: 0.02,
      other: 1.88,
    }),
  },
  {
    key: "salted-butter",
    name: "Salted butter",
    aliases: ["butter salted"],
    role: "fat",
    water: 15.9,
    solids: solids({
      fat: 80.8,
      protein: 0.9,
      sugars: 0.1,
      salt: 1.6,
      other: 0.7,
    }),
  },
  {
    key: "granulated-sugar",
    name: "Granulated sugar",
    aliases: ["sugar", "white sugar", "caster sugar", "cane sugar"],
    role: "sweetener",
    water: 0,
    solids: solids({ sugars: 100 }),
  },
  {
    key: "honey",
    name: "Honey",
    aliases: ["raw honey"],
    role: "sweetener",
    water: 17.1,
    solids: solids({ sugars: 82.1, other: 0.8 }),
  },
  {
    key: "sea-salt",
    name: "Fine sea salt",
    aliases: ["sea salt", "fine salt", "kosher salt", "salt"],
    role: "salt",
    water: 0,
    solids: solids({ salt: 100 }),
  },
  {
    key: "instant-yeast",
    name: "Instant yeast",
    aliases: ["active dry yeast", "dry yeast", "bread yeast", "yeast"],
    role: "other",
    water: 5,
    solids: solids({
      fat: 7.6,
      protein: 40,
      sugars: 8,
      starch: 20,
      fiber: 10,
      salt: 0.5,
      other: 8.9,
    }),
  },
  {
    key: "tomato",
    name: "Tomatoes",
    aliases: ["tomato", "plum tomatoes"],
    role: "other",
    water: 94.5,
    solids: solids({
      fat: 0.2,
      protein: 0.9,
      sugars: 2.6,
      starch: 0.55,
      fiber: 1.2,
      salt: 0.01,
      other: 0.04,
    }),
  },
  {
    key: "cherry-tomato",
    name: "Cherry tomatoes",
    aliases: ["cherry tomatoes", "cherry tomato"],
    role: "other",
    water: 94.5,
    solids: solids({
      fat: 0.2,
      protein: 0.9,
      sugars: 2.6,
      starch: 0.55,
      fiber: 1.2,
      salt: 0.01,
      other: 0.04,
    }),
  },
  {
    key: "rosemary",
    name: "Fresh rosemary",
    aliases: ["rosemary", "rosemary leaves"],
    role: "other",
    water: 67.8,
    solids: solids({
      fat: 5.9,
      protein: 3.3,
      starch: 12,
      fiber: 9,
      salt: 0.05,
      other: 1.95,
    }),
  },
  {
    key: "garlic",
    name: "Garlic",
    aliases: ["garlic cloves", "garlic clove", "fresh garlic"],
    role: "other",
    water: 58.6,
    solids: solids({
      fat: 0.5,
      protein: 6.4,
      sugars: 1,
      starch: 30.4,
      fiber: 2.1,
      salt: 0.04,
      other: 0.96,
    }),
  },
  {
    key: "egg",
    name: "Whole egg",
    aliases: ["egg", "eggs"],
    role: "other",
    water: 76.15,
    solids: solids({
      fat: 9.5,
      protein: 12.6,
      sugars: 0.4,
      salt: 0.36,
      other: 0.99,
    }),
  },
  {
    key: "egg-yolk",
    name: "Egg yolk",
    aliases: ["egg yolk", "egg yolks", "yolk", "yolks"],
    role: "other",
    water: 52.31,
    solids: solids({
      fat: 26.54,
      protein: 15.86,
      sugars: 0.56,
      salt: 0.12,
      other: 4.61,
    }),
  },
  {
    key: "egg-white",
    name: "Egg white",
    aliases: ["egg white", "egg whites"],
    role: "other",
    water: 87.57,
    solids: solids({
      fat: 0.17,
      protein: 10.9,
      sugars: 0.71,
      salt: 0.42,
      other: 0.23,
    }),
  },
  {
    key: "vanilla-extract",
    name: "Vanilla extract",
    aliases: ["vanilla", "pure vanilla extract"],
    role: "other",
    water: 52.6,
    solids: solids({ sugars: 12.7, other: 34.7 }),
  },
  {
    key: "baking-powder",
    name: "Baking powder",
    aliases: ["baking powder double acting", "double acting baking powder"],
    role: "other",
    water: 4,
    solids: solids({ starch: 27.7, salt: 12, other: 56.3 }),
  },
  {
    key: "mozzarella",
    name: "Mozzarella",
    aliases: ["fresh mozzarella", "mozzarella cheese"],
    role: "other",
    water: 50,
    solids: solids({
      fat: 22.4,
      protein: 22.2,
      sugars: 1,
      salt: 1.6,
      other: 2.8,
    }),
  },
  {
    key: "parmesan",
    name: "Parmesan",
    aliases: ["parmigiano reggiano", "parmesan cheese"],
    role: "other",
    water: 29,
    solids: solids({
      fat: 25.8,
      protein: 35.8,
      sugars: 0.9,
      salt: 1.6,
      other: 6.9,
    }),
  },
]

export const SAMPLE_RECIPE: RecipeDraft = {
  title: "Tomato & rosemary focaccia",
  servings: 8,
  ingredients: [
    { id: "flour", name: "Bread flour", grams: 500 },
    { id: "water", name: "Warm water", grams: 380 },
    { id: "oil", name: "Extra virgin olive oil", grams: 40 },
    { id: "salt", name: "Fine sea salt", grams: 10 },
    { id: "yeast", name: "Instant yeast", grams: 5 },
    { id: "honey", name: "Honey", grams: 8 },
    { id: "tomatoes", name: "Cherry tomatoes", grams: 120 },
    { id: "rosemary", name: "Fresh rosemary", grams: 4 },
  ],
  method:
    "Mix until no dry flour remains. Fold three times over 90 minutes, then proof in an oiled tray. Dimple, top, and bake until deeply golden.",
}
