"""Engine fixtures for Forkluck Recipes for Mac, generated by the real engines.

The Mac app ports the normalized costing engine (`domains/recipes/health.py`),
the nutrition rollup (`domains/recipes/nutrition.py`), `purchase_quantity`,
the FoodData Central adapter, the allergen hint parser and catalog activation
to Swift. Each test here runs the Python original over fixed inputs and pins
what it answers in `forkluck/parity/*.json`, which the Mac repository copies
into its test bundle and asserts its ports against.

Costing and nutrition read hand-authored scenarios from
`forkluck/parity/scenarios/`, in the engine-input shape the Mac snapshots
decode (keys are human slugs, never database ids). Every fixture records the
command that regenerates it:

    cd apps/api && UPDATE_ENGINE_FIXTURE=1 .venv/bin/python manage.py test forkluck.test_mac_parity_fixtures

Without the variable a missing file is written and an existing one is
asserted equal, so a change to an engine fails here until the fixture is
regenerated and copied across.
"""

import json
import os
from decimal import Decimal
from pathlib import Path
from types import SimpleNamespace
from typing import Any
from unittest import mock

from django.core import management
from django.test import SimpleTestCase, TestCase

from .domains.ingredients.actions import action_search_catalog_ingredients
from .domains.recipes.health import (
    PriceSource,
    RecipeHealthReadModel,
    _preparation_for,
    _standard_volume_ratio,
    catalog_measure_sources,
    labor_seconds_per_batch,
)
from .domains.recipes.nutrition import per_100g_nutrients, recipe_nutrition_payload
from .domains.shared import allergen_hints as hints_module
from .domains.shared.catalog_activation import materialize_catalog_ingredient
from .domains.shared.density import grams_for
from .domains.shared.ingredient_identity import qualifier_clauses
from .domains.shared.physical_expansion import (
    EquivalencyBasis,
    Measure,
    PreparationBasis,
    PurchaseBasis,
    purchase_quantity,
    recipe_batch_basis,
    recipe_measure_pairs,
    share_of_batch,
)
from .integrations import food_data
from .models import (
    BenchCostSettings,
    CatalogIngredient,
    CatalogIngredientAllergen,
    CatalogIngredientAlias,
    CatalogIngredientMeasure,
    CatalogPreparationMeasure,
    CatalogPreparationYield,
    Ingredient,
    IngredientAllergenOverride,
    IngredientConversion,
    IngredientMeasure,
    Preparation,
    Recipe,
    RecipeEquivalency,
    RecipeItem,
    RecipeStep,
    RecipeTiming,
    User,
    normalized_name,
)

PARITY = Path(__file__).resolve().parent / "parity"
GENERATOR = (
    "cd apps/api && UPDATE_ENGINE_FIXTURE=1 .venv/bin/python manage.py test"
    " forkluck.test_mac_parity_fixtures"
)


def _decimal(value: Any) -> Decimal | None:
    return None if value is None else Decimal(str(value))


def _plain(value: Any) -> Any:
    """JSON values only: Decimals as floats, tuples as lists."""
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, dict):
        return {str(key): _plain(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_plain(item) for item in value]
    return value


def pin(test: SimpleTestCase, name: str, cases: dict[str, Any]) -> None:
    """Write the fixture when asked to or when it is missing, then compare."""
    generated = json.loads(
        json.dumps({"generator": GENERATOR, **_plain(cases)}, allow_nan=False)
    )
    path = PARITY / name
    if os.environ.get("UPDATE_ENGINE_FIXTURE") or not path.exists():
        path.write_text(
            json.dumps(generated, indent=2, ensure_ascii=False, allow_nan=False) + "\n",
            encoding="utf-8",
        )
    test.assertEqual(json.loads(path.read_text(encoding="utf-8")), generated)


def _scenario(name: str) -> dict[str, Any]:
    return json.loads((PARITY / "scenarios" / name).read_text(encoding="utf-8"))


class Library:
    """A scenario document built into real rows for one user.

    Efficiency is stored as 100 where the scenario says 0, because the
    database refuses 0; `efficiency_overrides` carries the written value so
    the costing read can see it as the Mac editor would hold it.
    """

    def __init__(self, user: User, document: dict[str, Any]):
        self.user = user
        self.document = document
        self.ids: dict[str, str] = {}
        self.catalog: dict[str, CatalogIngredient] = {}
        self.ingredients: dict[str, Ingredient] = {}
        self.recipes: dict[str, Recipe] = {}
        self.items: dict[str, RecipeItem] = {}
        self.efficiency_overrides: dict[str, Decimal] = {}
        settings = document["settings"]
        BenchCostSettings.objects.update_or_create(
            user=user,
            defaults={
                "wage_per_hour_cents": settings["wagePerHourCents"],
                "food_cost_target_bps": settings["foodCostTargetBps"],
            },
        )
        for entry in document["catalog"]:
            self._catalog(entry)
        for entry in document["ingredients"]:
            self._ingredient(entry)
        for entry in document["recipes"]:
            self._recipe(entry)
        for entry in document["recipes"]:
            self._lines(entry)
        catalog_measure_sources.cache_clear()

    def _catalog(self, entry: dict[str, Any]) -> None:
        row = CatalogIngredient.objects.create(key=entry["key"], name=entry["name"])
        self.catalog[entry["key"]] = row
        for synonym in entry["synonyms"]:
            CatalogIngredientAlias.objects.create(
                ingredient=row,
                text=synonym,
                normalized_text=normalized_name(synonym),
                provenance="catalog",
            )
        for keys, status in ((entry["allergens"], "contains"), (entry["verify"], "checkLabel")):
            for key in keys:
                CatalogIngredientAllergen.objects.create(
                    ingredient=row,
                    allergen=key,
                    status=status,
                    source_kind="catalog",
                    source_ref=entry["key"],
                )
        for measure in entry["measures"]:
            CatalogIngredientMeasure.objects.create(
                ingredient=row,
                unit=measure["unit"],
                amount=_decimal(measure["amount"]),
                grams=_decimal(measure["grams"]),
                qualifier=measure["qualifier"],
                source_kind="catalog",
                source_ref=entry["key"],
                confidence=measure["confidence"],
                is_default=True,
            )

    def _ingredient(self, entry: dict[str, Any]) -> None:
        catalog = self.catalog.get(entry["catalogKey"]) if entry["catalogKey"] else None
        row = Ingredient.objects.create(
            user=self.user,
            name=entry["name"],
            status=entry["status"],
            non_edible=entry["nonEdible"],
            purchase_cost_cents=entry["purchaseCostCents"],
            purchase_size=_decimal(entry["purchaseSize"]),
            purchase_unit=entry["purchaseUnit"],
            yield_percent=_decimal(entry["yieldPercent"]),
            catalog_ingredient=catalog,
            nutrition_per_100g=entry["nutritionPer100g"],
            sugars_are_added=entry["sugarsAreAdded"],
            nutrition_label_name=entry["nutritionLabelName"],
        )
        self.ingredients[entry["key"]] = row
        self.ids[str(row.id)] = entry["key"]
        self.ids[row.public_id] = entry["key"]
        conversion = entry["conversion"]
        if conversion is not None:
            IngredientConversion.objects.create(
                user=self.user,
                ingredient=row,
                average_weight=conversion["usesStandard"],
                weight_amount=_decimal(conversion["weightAmount"]),
                weight_unit=conversion["weightUnit"],
                volume_amount=_decimal(conversion["volumeAmount"]),
                volume_unit=conversion["volumeUnit"],
                each_amount=_decimal(conversion["eachAmount"]),
                each_unit=conversion["eachUnit"],
                source=conversion["source"],
                confidence=conversion["confidence"],
            )
        for measure in entry["measures"]:
            IngredientMeasure.objects.create(
                ingredient=row,
                unit=measure["unit"],
                amount=_decimal(measure["amount"]),
                grams=_decimal(measure["grams"]),
                qualifier=normalized_name(measure["qualifier"]),
            )
        for preparation in entry["preparations"]:
            Preparation.objects.create(
                user=self.user,
                ingredient=row,
                name=preparation["name"],
                normalized_name=normalized_name(preparation["name"]),
                yield_percent=_decimal(preparation["yieldPercent"]),
                source=preparation["source"],
                average_weight=preparation["usesStandard"],
                weight_amount=_decimal(preparation["weightAmount"]),
                weight_unit=preparation["weightUnit"],
                volume_amount=_decimal(preparation["volumeAmount"]),
                volume_unit=preparation["volumeUnit"],
                each_amount=_decimal(preparation["eachAmount"]),
                each_unit=preparation["eachUnit"],
            )
        for allergen, status in entry["allergenOverrides"].items():
            IngredientAllergenOverride.objects.create(
                ingredient=row, allergen=allergen, status=status
            )

    def _recipe(self, entry: dict[str, Any]) -> None:
        row = Recipe.objects.create(
            user=self.user,
            title=entry["title"],
            kind=entry["kind"],
            status=entry["status"],
            yield_amount=entry["yieldAmount"],
            yield_unit=entry["yieldUnit"],
            serving_amount=_decimal(entry["servingAmount"]),
            serving_unit=entry["servingUnit"],
            menu_price_cents=entry["menuPriceCents"],
            nutrition_serving_amount=_decimal(entry["nutritionServingAmount"]),
            nutrition_serving_unit=entry["nutritionServingUnit"],
            nutrition_package_amount=_decimal(entry["nutritionPackageAmount"]),
            nutrition_package_unit=entry["nutritionPackageUnit"],
            prep_time_amount=_decimal(entry["prepTimeAmount"]),
            prep_time_unit=entry["prepTimeUnit"],
            auto_prep_time_enabled=entry["autoPrepTimeEnabled"],
        )
        self.recipes[entry["key"]] = row
        self.ids[str(row.id)] = entry["key"]
        self.ids[row.public_id] = entry["key"]
        equivalency = entry["equivalency"]
        if equivalency is not None:
            RecipeEquivalency.objects.create(
                recipe=row,
                mass_amount=_decimal(equivalency["massAmount"]),
                mass_unit=equivalency["massUnit"],
                volume_amount=_decimal(equivalency["volumeAmount"]),
                volume_unit=equivalency["volumeUnit"],
                count_amount=_decimal(equivalency["countAmount"]),
                count_unit=equivalency["countUnit"],
                standard=equivalency["standard"],
            )
        for position, step in enumerate(entry["steps"]):
            step_row = RecipeStep.objects.create(
                recipe=row,
                position=position,
                kind=step["kind"],
                title=step["title"],
                body=step["body"],
                labor_kind=step["laborKind"],
            )
            for timing in step["timings"]:
                RecipeTiming.objects.create(
                    step=step_row,
                    seconds=timing["seconds"],
                    yield_count=timing["yieldCount"],
                )

    def _lines(self, entry: dict[str, Any]) -> None:
        recipe = self.recipes[entry["key"]]
        for position, line in enumerate(entry["lines"]):
            efficiency = _decimal(line["efficiency"])
            item = RecipeItem.objects.create(
                recipe=recipe,
                position=position,
                kind=line["kind"],
                display_name=line["displayName"],
                quantity=_decimal(line["quantity"]),
                unit=line["unit"],
                preparation_note=line["preparationNote"],
                efficiency=efficiency if efficiency else Decimal(100),
                efficiency_after_cooking=_decimal(line["efficiencyAfterCooking"]),
                is_base=line["isBase"],
                excluded_from_cost=line["excludedFromCost"],
                ingredient=self.ingredients.get(line["ingredientKey"] or ""),
                subrecipe=self.recipes.get(line["subrecipeKey"] or ""),
            )
            if not efficiency:
                self.efficiency_overrides[str(item.id)] = efficiency
            self.items[line["key"]] = item
            self.ids[str(item.id)] = line["key"]

    def keyed(self, value: Any) -> Any:
        """The payload with every database id written as its scenario key."""
        if isinstance(value, dict):
            return {self.ids.get(key, key): self.keyed(item) for key, item in value.items()}
        if isinstance(value, list):
            return [self.keyed(item) for item in value]
        if isinstance(value, str):
            return self.ids.get(value, value)
        return value


def _purchase_issues(
    model: RecipeHealthReadModel, ingredient_id: str, quantity: float, unit: str, note: str
) -> list[str] | None:
    """The purchase_quantity issue codes behind one costing line, as
    `_sale_units_for` reaches them, so the "needs conversion" state is pinned."""
    match = model.by_id.get(ingredient_id)
    if match is None or match.is_component:
        return None
    preparation = _preparation_for(match, note)
    expansion = purchase_quantity(
        quantity,
        unit,
        PurchaseBasis(
            purchase_size=match.purchase_size,
            purchase_unit=match.purchase_unit,
            yield_percent=match.yield_percent,
            conversion=tuple(Measure(amount, pair) for amount, pair in match.conversion),
            conversion_is_automatic=match.conversion_is_automatic,
        ),
        PreparationBasis(
            yield_percent=preparation.yield_percent,
            conversion=tuple(
                Measure(amount, pair) for amount, pair in preparation.conversion
            ),
            conversion_is_automatic=preparation.conversion_is_automatic,
        )
        if preparation is not None
        else None,
        standard_bridge=lambda source, target: _standard_volume_ratio(
            source, target, match, "" if preparation is not None else note
        ),
    )
    return [issue.code for issue in expansion.issues]


class CostingParityFixtureTests(TestCase):
    """`costing-cases.json`: what the recipe list and Cost tab read, per recipe."""

    def test_costing_cases(self):
        user = User.objects.create_user(
            email="mac-costing@example.test", password="a-long-test-passphrase-2468"
        )
        scenario = _scenario("costing.json")
        library = Library(user, scenario)
        model = RecipeHealthReadModel(user)
        graph = model._owner_recipes()
        for recipe in graph.values():
            for item in recipe._normalized_items:
                override = library.efficiency_overrides.get(str(item.id))
                if override is not None:
                    item.efficiency = override

        expect: dict[str, Any] = {}
        for entry in scenario["recipes"]:
            recipe = graph[str(library.recipes[entry["key"]].id)]
            total, _issues, _declared = model._normalized_cost(recipe)
            row = model._normalized_row(recipe)
            seconds, untimed = labor_seconds_per_batch(recipe, recipe.steps.all())
            probes: dict[str, Any] = {}
            for line in entry["lines"]:
                item = library.items[line["key"]]
                if item.ingredient_id is None or item.quantity is None or not item.unit:
                    continue
                ingredient_id = str(item.ingredient_id)
                quantity = float(item.quantity)
                probes[line["key"]] = {
                    "ingredientCents": model.ingredient_cents(
                        ingredient_id, quantity, item.unit, item.preparation_note
                    ),
                    "lineGrams": model.line_grams(
                        ingredient_id,
                        quantity,
                        item.unit,
                        normalized_name(item.preparation_note),
                    ),
                    "purchaseIssues": _purchase_issues(
                        model, ingredient_id, quantity, item.unit, item.preparation_note
                    ),
                }
            expect[entry["key"]] = {
                "lineCosts": library.keyed(model.normalized_item_costs(recipe)),
                "total": total,
                "portionCents": row["ingredientCents"],
                "suffix": row["suffix"],
                "menuPriceCents": row["menuPriceCents"],
                "foodCost": row["foodCost"],
                "overTarget": row["overTarget"],
                "issues": row["issues"],
                "laborSeconds": seconds,
                "untimedSteps": untimed,
                "labor": row["labor"],
                "probes": probes,
            }
        pin(self, "costing-cases.json", {"scenario": scenario, "expect": expect})


class NutritionParityFixtureTests(TestCase):
    """`nutrition-cases.json`: the Nutrition tab's payload, per recipe."""

    def test_nutrition_cases(self):
        user = User.objects.create_user(
            email="mac-nutrition@example.test", password="a-long-test-passphrase-2468"
        )
        scenario = _scenario("nutrition.json")
        library = Library(user, scenario)
        ingredients = {
            entry["key"]: per_100g_nutrients(
                entry["nutritionPer100g"], sugars_are_added=entry["sugarsAreAdded"]
            )
            for entry in scenario["ingredients"]
            if entry["nutritionPer100g"] is not None
        }
        expect = {
            entry["key"]: library.keyed(
                recipe_nutrition_payload(
                    Recipe.objects.get(id=library.recipes[entry["key"]].id), user
                )
            )
            for entry in scenario["recipes"]
        }
        pin(
            self,
            "nutrition-cases.json",
            {"scenario": scenario, "per100gNutrients": ingredients, "expect": expect},
        )


# Catalog keys activated from the shipped catalog: plain entries, entries with
# several default measures in each family, and entries whose preparations carry
# their own measures.
ACTIVATED_KEYS = [
    "water",
    "onion",
    "garlic",
    "egg",
    "butter",
    "leek",
    "carrot",
    "celery",
    "tomato-paste",
    "zucchini",
    "bell-pepper-red",
    "cabbage",
    "spinach",
    "shallot",
    "scallion",
    "potato",
    "sweet-potato",
    "tomato",
    "cucumber",
    "eggplant",
    "napa-cabbage",
    "oats",
    "mayonnaise",
    "fish-sauce",
    "worcestershire",
]

SEARCHES = ["onion", "jarlic", "garl", "flour", "sugar", "egg", "ch", "pepper", "o"]


def _catalog_json(row: CatalogIngredient) -> dict[str, Any]:
    measures = CatalogIngredientMeasure.objects.filter(
        ingredient=row, is_active=True, is_default=True
    ).order_by("created_at", "id")
    yields = CatalogPreparationYield.objects.filter(ingredient=row, is_active=True).order_by(
        "normalized_name"
    )
    return {
        "key": row.key,
        "name": row.name,
        "normalizedName": row.normalized_name,
        "aliases": sorted(
            CatalogIngredientAlias.objects.filter(ingredient=row, is_active=True).values_list(
                "text", flat=True
            )
        ),
        "allergens": {
            allergen.allergen: allergen.status
            for allergen in CatalogIngredientAllergen.objects.filter(
                ingredient=row, is_active=True
            ).order_by("allergen")
        },
        "measures": [
            {
                "unit": measure.unit,
                "amount": measure.amount,
                "grams": measure.grams,
                "confidence": measure.confidence,
                "sourceRef": measure.source_ref,
            }
            for measure in measures
        ],
        "preparations": [
            {
                "name": prep.name,
                "normalizedName": prep.normalized_name,
                "yieldPercent": prep.yield_percent,
                "confidence": prep.confidence,
                "measures": [
                    {
                        "unit": measure.unit,
                        "amount": measure.amount,
                        "grams": measure.grams,
                        "confidence": measure.confidence,
                    }
                    for measure in prep.measures.filter(is_active=True, is_default=True).order_by(
                        "created_at", "id"
                    )
                ],
            }
            for prep in yields
        ],
    }


def _pairs(row: Any) -> dict[str, Any]:
    return {
        "usesStandard": row.average_weight,
        "weightAmount": row.weight_amount,
        "weightUnit": row.weight_unit,
        "volumeAmount": row.volume_amount,
        "volumeUnit": row.volume_unit,
        "eachAmount": row.each_amount,
        "eachUnit": row.each_unit,
    }


def _activated_json(row: Ingredient) -> dict[str, Any]:
    conversion = IngredientConversion.objects.filter(ingredient=row).first()
    return {
        "name": row.name,
        "normalizedName": row.normalized_name,
        "catalogKey": row.catalog_ingredient.key if row.catalog_ingredient else None,
        "purchaseCostCents": row.purchase_cost_cents,
        "purchaseSize": row.purchase_size,
        "purchaseUnit": row.purchase_unit,
        "yieldPercent": row.yield_percent,
        "measures": [
            {
                "unit": measure.unit,
                "amount": measure.amount,
                "grams": measure.grams,
                "qualifier": measure.qualifier,
            }
            for measure in IngredientMeasure.objects.filter(ingredient=row).order_by(
                "created_at", "id"
            )
        ],
        "conversion": (
            {
                **_pairs(conversion),
                "source": conversion.source,
                "confidence": conversion.confidence,
            }
            if conversion is not None
            else None
        ),
        "preparations": [
            {
                "name": prep.name,
                "normalizedName": prep.normalized_name,
                "yieldPercent": prep.yield_percent,
                "source": prep.source,
                "confidence": prep.confidence,
                **_pairs(prep),
            }
            for prep in Preparation.objects.filter(ingredient=row).order_by("normalized_name")
        ],
    }


class CatalogActivationFixtureTests(TestCase):
    """`catalog-activation-cases.json`: the shipped catalog loaded by
    `sync_catalog`, then "Add from catalog" for a spread of entries."""

    def test_catalog_activation_cases(self):
        management.call_command("sync_catalog", verbosity=0)
        # Searched before the hand-made entry below exists, so only the
        # shipped catalog answers.
        searcher = User.objects.create_user(
            email="mac-catalog-search@example.test", password="a-long-test-passphrase-2468"
        )
        searches = []
        for query in SEARCHES:
            try:
                items = action_search_catalog_ingredients(searcher, {"query": query})["items"]
                result: Any = [
                    {
                        "key": CatalogIngredient.objects.get(id=item["id"]).key,
                        "name": item["name"],
                        "aliases": item["aliases"],
                    }
                    for item in items
                ]
            except ValueError as error:
                result = {"error": str(error)}
            searches.append({"query": query, "expect": result})

        user = User.objects.create_user(
            email="mac-catalog@example.test", password="a-long-test-passphrase-2468"
        )
        # The shipped file carries no yields, so a yield-only preparation and
        # a yield beside measures are pinned on one extra, hand-made entry.
        extra = CatalogIngredient.objects.create(key="parity-garlic", name="Parity garlic")
        CatalogIngredientMeasure.objects.create(
            ingredient=extra,
            unit="clove",
            amount=Decimal(1),
            grams=Decimal(3),
            source_kind="catalog",
            source_ref="parity",
            confidence="high",
            is_default=True,
        )
        for name, percent, measures in (
            ("Minced", Decimal("88"), []),
            ("Roasted", Decimal("70"), [("cup", Decimal(1), Decimal(140))]),
        ):
            prep = CatalogPreparationYield.objects.create(
                ingredient=extra,
                name=name,
                normalized_name=normalized_name(name),
                yield_percent=percent,
                source_kind="catalog",
                source_ref="parity",
                source_release="parity",
                derivation="catalog",
                evidence_count=1,
                confidence="low",
                is_default=True,
            )
            for unit, amount, grams in measures:
                CatalogPreparationMeasure.objects.create(
                    preparation_yield=prep,
                    unit=unit,
                    amount=amount,
                    grams=grams,
                    source_kind="catalog",
                    source_ref="parity",
                    confidence="low",
                    is_default=True,
                )

        cases = []
        for key in [*ACTIVATED_KEYS, "parity-garlic"]:
            catalog = CatalogIngredient.objects.get(key=key)
            row, created, measures, preparations = materialize_catalog_ingredient(
                user, catalog
            )
            _again, created_again, _measures, preparations_again = (
                materialize_catalog_ingredient(user, catalog)
            )
            cases.append(
                {
                    "key": key,
                    "catalog": _catalog_json(catalog),
                    "created": created,
                    "measureCount": measures,
                    "preparationsSeeded": preparations,
                    "again": {"created": created_again, "preparationsSeeded": preparations_again},
                    "ingredient": _activated_json(row),
                }
            )

        # A pantry row already named like a catalog entry adopts it.
        adopted = Ingredient.objects.create(
            user=user,
            name="Lemon",
            purchase_cost_cents=250,
            purchase_size=Decimal(1),
            purchase_unit="kg",
        )
        adopted_row, adopted_created, _, _ = materialize_catalog_ingredient(
            user, CatalogIngredient.objects.get(normalized_name=adopted.normalized_name)
        )

        pin(
            self,
            "catalog-activation-cases.json",
            {
                "activations": cases,
                "adoption": {
                    "created": adopted_created,
                    "ingredient": _activated_json(adopted_row),
                },
                "searches": searches,
            },
        )


# The FoodData Central payloads, package texts and typed labels that
# test_food_data.py hands to the adapter and the hint parser, captured from its
# run and written out here.
FOODS = [{'dataType': 'Branded',
  'description': 'ORGANIC TAMARI',
  'brandOwner': 'San-J',
  'foodNutrients': [{'nutrientId': 1003, 'value': 10},
                    {'nutrientId': 1004, 'value': 0},
                    {'nutrientId': 1005, 'value': 5},
                    {'nutrientId': 1093, 'value': 5000},
                    {'nutrientId': 1110, 'value': 40}]},
 {'foodNutrients': [{'nutrient': {'id': 1003}, 'amount': 10},
                    {'nutrient': {'id': 1004}, 'amount': 1},
                    {'nutrient': {'id': 1005}, 'amount': 76},
                    {'nutrient': {'id': 1051}, 'amount': 12},
                    {'nutrient': {'id': 1093}, 'amount': 2}]},
 {'foodNutrients': [{'nutrient': {'id': 1051}, 'amount': 0.2},
                    {'nutrient': {'id': 1007}, 'amount': 36.9},
                    {'nutrient': {'id': 1093}, 'amount': 27400}]},
 {'foodNutrients': [{'nutrient': {'id': 1051}, 'amount': 0.42},
                    {'nutrient': {'id': 1093}, 'amount': 38700}]},
 {'foodNutrients': [{'nutrient': {'id': 1051}, 'amount': 12},
                    {'nutrient': {'id': 1003}, 'amount': 10},
                    {'nutrient': {'id': 1004}, 'amount': 1},
                    {'nutrient': {'id': 1005}, 'amount': 76},
                    {'nutrient': {'id': 2000}, 'amount': 0.3}],
  'dataType': 'Foundation'},
 {'foodNutrients': [{'nutrient': {'id': 1051}, 'amount': 12},
                    {'nutrient': {'id': 1003}, 'amount': 10},
                    {'nutrient': {'id': 1004}, 'amount': 1},
                    {'nutrient': {'id': 1005}, 'amount': 76},
                    {'nutrient': {'id': 2000}, 'amount': 0.3}],
  'dataType': 'SR Legacy'},
 {'foodNutrients': [{'nutrient': {'id': 1051}, 'amount': 12},
                    {'nutrient': {'id': 1003}, 'amount': 10},
                    {'nutrient': {'id': 1004}, 'amount': 1},
                    {'nutrient': {'id': 1005}, 'amount': 76},
                    {'nutrient': {'id': 2000}, 'amount': 0.3},
                    {'nutrient': {'id': 1235}, 'amount': 4}],
  'dataType': 'SR Legacy'},
 {'foodNutrients': [{'nutrient': {'id': 1051}, 'amount': 12},
                    {'nutrient': {'id': 1003}, 'amount': 10},
                    {'nutrient': {'id': 1004}, 'amount': 1},
                    {'nutrient': {'id': 1005}, 'amount': 76},
                    {'nutrient': {'id': 2000}, 'amount': 0.3}],
  'dataType': 'Survey (FNDDS)'},
 {'foodNutrients': [{'nutrient': {'id': 1003}, 'amount': 20},
                    {'nutrient': {'id': 1004}, 'amount': 10},
                    {'nutrient': {'id': 1005}, 'amount': 30},
                    {'nutrient': {'id': 1051}, 'amount': 35},
                    {'nutrient': {'id': 1093}, 'amount': 400},
                    {'nutrient': {'id': 1258}, 'amount': 12}]},
 {'foodNutrients': [{'nutrient': {'id': 1003}, 'amount': 20},
                    {'nutrient': {'id': 1004}, 'amount': 10},
                    {'nutrient': {'id': 1005}, 'amount': 30},
                    {'nutrient': {'id': 1051}, 'amount': 35},
                    {'nutrient': {'id': 1079}, 'amount': 5},
                    {'nutrient': {'id': 1093}, 'amount': 400},
                    {'nutrient': {'id': 2000}, 'amount': 3}]},
 {'dataType': 'Foundation',
  'foodNutrients': [{'nutrient': {'id': 1085}, 'amount': 94.5},
                    {'nutrient': {'id': 1258}, 'amount': 6.61}]},
 {'foodNutrients': [{'nutrient': {'id': 1003}, 'amount': 20},
                    {'nutrient': {'id': 1004}, 'amount': 10},
                    {'nutrient': {'id': 1005}, 'amount': 30},
                    {'nutrient': {'id': 1051}, 'amount': 35},
                    {'nutrient': {'id': 1079}, 'amount': 5},
                    {'nutrient': {'id': 1093}, 'amount': 400},
                    {'nutrient': {'id': 2000}, 'amount': 3},
                    {'nutrient': {'id': 1258}, 'amount': 6}]},
 {'foodNutrients': [{'nutrient': {'id': 1003}, 'amount': 20},
                    {'nutrient': {'id': 1004}, 'amount': 10},
                    {'nutrient': {'id': 1005}, 'amount': 30}]},
 {'dataType': 'Branded',
  'description': 'SANDWICH COOKIES',
  'ingredients': '  ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE '
                 'MONONITRATE, RIBOFLAVIN, FOLIC ACID), SUGAR, PEANUT BUTTER (PEANUTS, '
                 'CORN SYRUP SOLIDS, SALT), SOYBEAN OIL, HIGH FRUCTOSE CORN SYRUP, SOY '
                 'LECITHIN (EMULSIFIER), VANILLIN - AN ARTIFICIAL FLAVOR. CONTAINS: '
                 'WHEAT, PEANUT, AND SOY.  ',
  'foodNutrients': [{'nutrientId': 1003, 'value': 5}]},
 {'dataType': 'Foundation',
  'description': 'Apples, raw',
  'foodNutrients': [{'nutrientId': 1003, 'value': 0},
                    {'nutrientId': 1051, 'value': 85}]},
 {'dataType': 'Branded',
  'description': 'LONG',
  'ingredients': 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, '
                 'SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, SALT, ',
  'foodNutrients': [{'nutrientId': 1003, 'value': 5}]}]

# Beyond the suite: a foundation and a branded record naming every nutrient id
# the adapter reads, the fallback ids, and energy stated only as 2047/2048.
FOODS += [
    {
        "dataType": "Foundation",
        "foodNutrients": [
            {"nutrient": {"id": nutrient_id}, "amount": amount}
            for nutrient_id, amount in (
                (1051, 60.2), (1003, 12.4), (1004, 10.1), (1005, 14.2), (1079, 2.1),
                (2000, 3.3), (1093, 320), (1007, 1.4), (1018, 0.5), (1258, 11.5),
                (1008, 190), (1257, 0.3), (1253, 45), (1442, 1.2), (1114, 0.8),
                (1087, 120), (1089, 1.9), (1092, 250),
            )
        ],
    },
    {
        "dataType": "Branded",
        "description": "GRANOLA BAR",
        "brandName": "Trail Co",
        "ingredients": "OATS, HONEY, ALMONDS. MAY CONTAIN PEANUTS.",
        "foodNutrients": [
            {"nutrientId": nutrient_id, "value": amount}
            for nutrient_id, amount in (
                (1003, 8), (1085, 18), (1050, 64), (2033, 6), (1063, 25), (1093, 180),
                (1008, 450), (1235, 20), (1110, 80), (1087, 40), (1089, -2), (1092, 300),
            )
        ],
    },
    {
        "dataType": "Foundation",
        "foodNutrients": [
            {"nutrient": {"id": nutrient_id}, "amount": amount}
            for nutrient_id, amount in (
                (1051, 75), (1003, 20), (1004, 3), (1005, 0), (1093, 60), (2047, 115), (2048, 118),
            )
        ],
    },
    {"dataType": "Foundation", "foodNutrients": "not a list"},
]


RANKINGS = [{'query': 'tamari',
  'matches': [{'fdcId': 9,
               'description': 'TAMARI',
               'dataType': 'Branded',
               'brand': 'San-J'}]},
 {'query': 'ground pork',
  'matches': [{'fdcId': 123,
               'description': 'PORK, GROUND',
               'dataType': 'Foundation',
               'brand': ''}]},
 {'query': 'sugar',
  'matches': [{'fdcId': 1,
               'description': 'Beverages, tea, with sugar',
               'dataType': 'SR Legacy',
               'brand': ''},
              {'fdcId': 2,
               'description': 'Gum drops, no sugar',
               'dataType': 'SR Legacy',
               'brand': ''},
              {'fdcId': 3,
               'description': 'Sugar, white, granulated or lump',
               'dataType': 'Survey (FNDDS)',
               'brand': ''},
              {'fdcId': 4,
               'description': 'Sugars, granulated',
               'dataType': 'Foundation',
               'brand': ''},
              {'fdcId': 5,
               'description': 'Honey',
               'dataType': 'Foundation',
               'brand': ''}]}]

LABELS = [{'values': {'calories': 100,
             'fat': 11,
             'saturatedFat': 7,
             'sodiumMg': 90,
             'totalCarbohydrate': 0,
             'sugars': 0,
             'protein': 0,
             'transFat': 0,
             'cholesterolMg': 30,
             'fiber': None,
             'addedSugars': None,
             'vitaminDMcg': None,
             'calciumMg': None,
             'ironMg': None,
             'potassiumMg': None},
  'servingGrams': 14},
 {'values': {'calories': 1}, 'servingGrams': 0}]

HINT_TEXTS = ['',
 '   ',
 'WATER, SUGAR, SALT.',
 'SESAME MEAL, PALM SHORTENING (NON-HYDROGENATED), CHOCOLATE CHIP (EVAPORATED CANE '
 'JUICE, NATURAL CHOCOLATE LIQUOR, COCOA BUTTER), WATER, CHICORY EXTRACT, FLAX MEAL, '
 'BAKING POWDER (ALUMINUM-FREE, GLUTEN-FREE), SEA SALT, BAKING SODA (ALUMINUM-FREE, '
 'GLUTEN FREE)',
 'WHEAT FLOUR, MILK. CONTAINS: MILK. MAY CONTAIN MILK AND SOY.',
 'SUGAR, COCOA MASS, COCOA BUTTER, SUNFLOWER LECITHIN. MAY CONTAIN MILK, HAZELNUTS AND '
 'WHEAT.',
 'DISTILLED VINEGAR, WATER, MOLASSES, SUGAR, SALT, SPICES, CITRIC ACID, ANCHOVY '
 '(FISH), CELERY SEED, NATURAL FLAVOR (CONTAINS SOY), XANTHAN GUM (THICKENER), GARLIC '
 'POWDER & TAMARIND EXTRACT.',
 'ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, '
 'FOLIC ACID), SUGAR, PEANUT BUTTER (PEANUTS, CORN SYRUP SOLIDS, SALT), SOYBEAN OIL, '
 'HIGH FRUCTOSE CORN SYRUP, SOY LECITHIN (EMULSIFIER), VANILLIN - AN ARTIFICIAL '
 'FLAVOR. CONTAINS: WHEAT, PEANUT, AND SOY.',
 'water, milk, salt',
 'water, egg, salt',
 'water, fish, salt',
 'water, shrimp, salt',
 'water, clam, salt',
 'water, almond, salt',
 'water, peanut, salt',
 'water, wheat, salt',
 'water, soy, salt',
 'water, sesame, salt',
 'water, sulfite, salt',
 'water, mustard, salt',
 'water, celery, salt',
 'water, lupin, salt',
 'Eggplant, maltodextrin',
 'eggs, ALMONDS',
 'Sodium Metabisulfite',
 'SULFUR DIOXIDE',
 'OATS, RAISINS. MANUFACTURED IN A FACILITY THAT ALSO PROCESSES PEANUTS.',
 'RICE FLOUR, SALT. PRODUCED ON SHARED EQUIPMENT WITH SOY.',
 'RICE FLOUR. MAY ALSO CONTAIN SESAME SEEDS.',
 'PEANUT BUTTER',
 'ALMOND MILK',
 'GLUTEN FREE OATS',
 'COCONUT MILK, WATER',
 'ALMOND MILK, SEA SALT',
 'OAT MILK',
 'SOY MILK',
 'RICE MILK',
 'SUGAR, COCOA BUTTER',
 'SHEA BUTTER',
 'PEANUT BUTTER, SALT',
 'ALMOND BUTTER',
 'ORGANIC NUT BUTTER',
 'BUTTERNUT SQUASH',
 'BAKING SODA, CREAM OF TARTAR',
 'WATER, WHEAT, SOYBEANS, SALT. MAY CONTAIN FISH.']


# Extra ranking cases beyond test_food_data.py: ties broken by data type, then
# by the order FDC sent.
RANKINGS += [
    {
        "query": "butter, salted",
        "matches": [
            {"fdcId": 11, "description": "Cookies, butter", "dataType": "SR Legacy", "brand": ""},
            {"fdcId": 12, "description": "Butter, salted", "dataType": "SR Legacy", "brand": ""},
            {"fdcId": 13, "description": "Butter, salted", "dataType": "Foundation", "brand": ""},
            {"fdcId": 14, "description": "Peanut butter", "dataType": "Branded", "brand": "Jif"},
            {"fdcId": 15, "description": "BUTTERMILK, SALTED", "dataType": "Branded", "brand": ""},
        ],
    },
    {"query": "", "matches": [{"fdcId": 1, "description": "Anything", "dataType": "", "brand": ""}]},
]

# Search responses as FDC sends them, for the brand and the page size.
SEARCH_RESPONSES = [
    {
        "query": "tamari",
        "scope": "branded",
        "foods": [
            {"fdcId": 9, "description": "TAMARI", "dataType": "Branded", "brandOwner": "San-J"},
            {"fdcId": 10, "description": "TAMARI SAUCE", "dataType": "Branded", "brandName": "  Kikkoman  "},
            {"fdcId": "11", "description": "Bad id", "dataType": "Branded"},
            {"fdcId": 12, "description": "Long brand", "dataType": "Branded", "brandOwner": "B" * 130},
        ],
    },
    {
        "query": "sugar",
        "scope": "common",
        "foods": [
            {"fdcId": index, "description": f"Sugar sample {index}", "dataType": "SR Legacy"}
            for index in range(1, 12)
        ],
    },
]

# Details as get_food receives them: a description, a brand, package text.
DETAILS = [
    {
        "description": "  Butter, salted  ",
        "dataType": "Foundation",
        "foodNutrients": FOODS[4]["foodNutrients"],
    },
    {
        "description": "ORGANIC TAMARI",
        "dataType": "Branded",
        "brandOwner": "San-J",
        "ingredients": "  WATER, ORGANIC SOYBEANS, SALT, ORGANIC ALCOHOL.  ",
        "foodNutrients": FOODS[0]["foodNutrients"],
    },
    {
        "description": "D" * 250,
        "dataType": "Branded",
        "brandName": "Brand",
        "ingredients": "I" * 4100,
        "foodNutrients": FOODS[0]["foodNutrients"],
    },
    {"description": 42, "foodNutrients": []},
]

# Typed labels beyond test_food_data.py.
LABELS += [
    {
        "values": {
            "calories": 250,
            "fat": 12,
            "saturatedFat": 14,
            "sodiumMg": 480,
            "totalCarbohydrate": 30,
            "fiber": 2,
            "sugars": 12,
            "addedSugars": 10,
            "protein": 5,
        },
        "servingGrams": 55,
    },
    {"values": {"calories": 0}, "servingGrams": -1},
]

# Allergen hints: every keyword of the table on its own, and the texts above.
KEYWORD_TEXTS = [
    f"water, {keyword}, salt"
    for keywords in hints_module.KEYWORDS.values()
    for keyword in keywords
]

# Ingredients for ingredient_allergen_hints, as the row, its catalog defaults
# and its overrides, from IngredientAllergenHintTests.
HINT_INGREDIENTS = [
    {"package": "WATER, WHEAT, SOYBEANS, SALT. MAY CONTAIN FISH.", "catalog": {}, "overrides": {}, "nonEdible": False},
    {
        "package": "WATER, WHEAT, SOYBEANS, SALT. MAY CONTAIN FISH.",
        "catalog": {"sulphites": "checkLabel"},
        "overrides": {},
        "nonEdible": False,
    },
    {
        "package": "WATER, WHEAT, SOYBEANS, SALT. MAY CONTAIN FISH.",
        "catalog": {"sulphites": "checkLabel"},
        "overrides": {"wheat": "contains", "fish": "doesNotContain", "sulphites": "mayContain"},
        "nonEdible": False,
    },
    {
        "package": "WATER, WHEAT, SOYBEANS, SALT. MAY CONTAIN FISH.",
        "catalog": {"soy": "contains"},
        "overrides": {},
        "nonEdible": False,
    },
    {
        "package": "WATER, WHEAT, SOYBEANS, SALT. MAY CONTAIN FISH.",
        "catalog": {"soy": "checkLabel"},
        "overrides": {},
        "nonEdible": False,
    },
    {
        "package": "WATER, WHEAT, SOYBEANS, SALT. MAY CONTAIN FISH.",
        "catalog": {"sulphites": "checkLabel"},
        "overrides": {},
        "nonEdible": True,
    },
    {"package": "", "catalog": {"milk": "contains", "egg": "mayContain"}, "overrides": {}, "nonEdible": False},
    {"package": "", "catalog": None, "overrides": {"peanut": "contains"}, "nonEdible": False},
]


def _purchase_basis(value: dict[str, Any]) -> PurchaseBasis:
    return PurchaseBasis(
        purchase_size=value["purchaseSize"],
        purchase_unit=value["purchaseUnit"],
        yield_percent=value["yieldPercent"],
        conversion=tuple(Measure(pair["amount"], pair["unit"]) for pair in value["conversion"]),
        conversion_is_automatic=value["conversionIsAutomatic"],
    )


def _source(size, unit, *, yield_percent=None, pairs=(), automatic=True):
    return {
        "purchaseSize": size,
        "purchaseUnit": unit,
        "yieldPercent": yield_percent,
        "conversion": [{"amount": amount, "unit": pair} for amount, pair in pairs],
        "conversionIsAutomatic": automatic,
    }


def _prep(yield_percent=None, pairs=(), automatic=True):
    return {
        "yieldPercent": yield_percent,
        "conversion": [{"amount": amount, "unit": pair} for amount, pair in pairs],
        "conversionIsAutomatic": automatic,
    }


CASE_OF_EGGS = _source(1, "case", pairs=[(36, "each")], automatic=False)
BLOCK_OF_BUTTER = _source(1, "lb", pairs=[(227, "g"), (1, "cup")], automatic=False)
CABBAGE = _source(1000, "g", pairs=[(8, "cup")], automatic=False)
SHREDDED = _prep(None, [(1000, "g"), (4, "cup")], automatic=False)
TOMATOES = _source(10, "lb", yield_percent=90)

# purchase_quantity inputs: test_physical_expansion.py, then the saleUnitsFor
# scenarios of apps/web/tests/pricing.test.ts, then every issue code. A
# `bridge` names the density lookup the costing read passes as its standard
# bridge (`_standard_volume_ratio`): the name the chart is read with and the
# qualifier that blocks it.
PURCHASES = [
    {"amount": 100, "unit": "g", "source": _source(1000, "g", yield_percent=80), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "cup", "source": _source(1, "kg", automatic=False), "preparation": None, "bridge": None},
    {"amount": 2, "unit": "each", "source": CASE_OF_EGGS, "preparation": None, "bridge": None},
    {"amount": 2, "unit": "case", "source": CASE_OF_EGGS, "preparation": None, "bridge": None},
    {"amount": 20, "unit": "g", "source": CASE_OF_EGGS, "preparation": None, "bridge": None},
    {
        "amount": 900,
        "unit": "g",
        "source": _source(1, "case", pairs=[(1800, "g"), (36, "each")], automatic=False),
        "preparation": None,
        "bridge": None,
    },
    {"amount": 1, "unit": "cup", "source": BLOCK_OF_BUTTER, "preparation": None, "bridge": None},
    {"amount": 227, "unit": "g", "source": BLOCK_OF_BUTTER, "preparation": None, "bridge": None},
    {
        "amount": 1,
        "unit": "cup",
        "source": {**BLOCK_OF_BUTTER, "purchaseSize": 25, "purchaseUnit": "kg"},
        "preparation": None,
        "bridge": None,
    },
    {
        "amount": 1,
        "unit": "cup",
        "source": {**BLOCK_OF_BUTTER, "purchaseSize": 1, "purchaseUnit": "each"},
        "preparation": None,
        "bridge": None,
    },
    {"amount": 3, "unit": "each", "source": _source(1, "case"), "preparation": None, "bridge": {"name": "eggs", "qualifier": ""}},
    {"amount": 1, "unit": "cup", "source": _source(1, "kg"), "preparation": None, "bridge": {"name": "flour", "qualifier": ""}},
    {"amount": 100, "unit": "g", "source": _source(1, "l"), "preparation": None, "bridge": {"name": "milk", "qualifier": ""}},
    {
        "amount": 100,
        "unit": "g",
        "source": _source(1, "l", pairs=[(4, "each")], automatic=False),
        "preparation": None,
        "bridge": {"name": "milk", "qualifier": ""},
    },
    {"amount": 100, "unit": "g", "source": _source(1, "l"), "preparation": None, "bridge": {"name": "milk", "qualifier": "scalded"}},
    {"amount": 200, "unit": "g", "source": _source(1, "kg"), "preparation": None, "bridge": {"name": "flour", "qualifier": ""}},
    {"amount": 2, "unit": "cup", "source": CABBAGE, "preparation": SHREDDED, "bridge": None},
    {"amount": 2, "unit": "cup", "source": CABBAGE, "preparation": _prep(None, [(4, "cup")], automatic=False), "bridge": None},
    {"amount": 250, "unit": "g", "source": CABBAGE, "preparation": _prep(None, [], automatic=False), "bridge": None},
    {"amount": 100, "unit": "g", "source": _source(1000, "g"), "preparation": _prep(88), "bridge": None},
    {"amount": 2, "unit": "cup", "source": CABBAGE, "preparation": _prep(50), "bridge": None},
    {"amount": 2, "unit": "cup", "source": CABBAGE, "preparation": None, "bridge": None},
    {"amount": 1, "unit": "lb", "source": TOMATOES, "preparation": None, "bridge": None},
    {"amount": 1, "unit": "lb", "source": {**TOMATOES, "yieldPercent": 100}, "preparation": None, "bridge": None},
    {"amount": 1, "unit": "lb", "source": TOMATOES, "preparation": _prep(50), "bridge": None},
    {"amount": 200, "unit": "g", "source": _source(1, "gal"), "preparation": None, "bridge": {"name": "canola oil", "qualifier": ""}},
    {"amount": 200, "unit": "g", "source": _source(1, "gal"), "preparation": None, "bridge": {"name": "canola oil", "qualifier": " "}},
    {"amount": 2, "unit": "pcs", "source": _source(1, "dozen"), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "slice", "source": _source(8, "each"), "preparation": None, "bridge": None},
    {
        "amount": 3,
        "unit": "each",
        "source": _source(1, "kg", pairs=[(120, "g"), (1, "each")], automatic=False),
        "preparation": None,
        "bridge": None,
    },
    {
        "amount": 2,
        "unit": "cup",
        "source": _source(1, "kg", pairs=[(4, "cup"), (2, "each")], automatic=False),
        "preparation": None,
        "bridge": None,
    },
    {
        "amount": 2,
        "unit": "cup",
        "source": _source(1, "case", pairs=[(4, "cup"), (2, "each")], automatic=False),
        "preparation": None,
        "bridge": None,
    },
    {
        "amount": 2,
        "unit": "cup",
        "source": _source(1, "kg"),
        "preparation": _prep(None, [(4, "cup"), (2, "each")], automatic=False),
        "bridge": None,
    },
    {"amount": 2, "unit": "cup", "source": _source(1, "kg", pairs=[(4, "cup")], automatic=False), "preparation": None, "bridge": None},
    {"amount": None, "unit": "g", "source": _source(1, "kg"), "preparation": None, "bridge": None},
    {"amount": 0, "unit": "g", "source": _source(1, "kg"), "preparation": None, "bridge": None},
    {"amount": -1, "unit": "g", "source": _source(1, "kg"), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "", "source": _source(1, "kg"), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "g", "source": _source(None, "kg"), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "g", "source": _source(0, "kg"), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "g", "source": _source(1, None), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "g", "source": _source(1, "kg"), "preparation": _prep(0), "bridge": None},
    {"amount": 1, "unit": "g", "source": _source(1, "kg", yield_percent=0), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "bushel", "source": _source(1, "bushel"), "preparation": None, "bridge": None},
    {"amount": 1, "unit": "bushel", "source": _source(1, "kg"), "preparation": None, "bridge": {"name": "apples", "qualifier": ""}},
]

MEASURE_PAIRS = [
    {"yieldAmount": 2, "yieldUnit": "kg", "equivalency": {"mass": [1000, "g"], "volume": [1, "l"], "count": None, "standard": True}},
    {"yieldAmount": 2.75, "yieldUnit": "cup", "equivalency": {"mass": [700, "g"], "volume": None, "count": [8, "each"], "standard": False}},
    {"yieldAmount": 1600, "yieldUnit": "ml", "equivalency": {"mass": [8, "oz"], "volume": [1, "cup"], "count": None, "standard": True}},
    {"yieldAmount": 12, "yieldUnit": "pcs", "equivalency": {"mass": [50, "g"], "volume": None, "count": [1, "each"], "standard": True}},
    {"yieldAmount": 12, "yieldUnit": "pcs", "equivalency": None},
    {"yieldAmount": None, "yieldUnit": "g", "equivalency": {"mass": [400, "g"], "volume": None, "count": [31, "pcs"], "standard": False}},
    {"yieldAmount": None, "yieldUnit": "g", "equivalency": {"mass": [400, "g"], "volume": None, "count": None, "standard": True}},
    {"yieldAmount": 0, "yieldUnit": "g", "equivalency": None},
    {"yieldAmount": 1, "yieldUnit": "kg", "equivalency": {"mass": None, "volume": [2, "l"], "count": None, "standard": True}},
    {"yieldAmount": 8, "yieldUnit": "slice", "equivalency": {"mass": [900, "g"], "volume": None, "count": [4, "each"], "standard": True}},
    {"yieldAmount": 3, "yieldUnit": "portion", "equivalency": None},
]

SHARES = [
    (250, "g"),
    (6, "pcs"),
    (2, "each"),
    (1, "slice"),
    (250, "ml"),
    (1, "cup"),
    (0, "g"),
    (None, "g"),
    (1, "bushel"),
]

NAMES = [
    "  Bread Flour ",
    "Crème Fraîche",
    "Jalapeño",
    "püree",
    "Extra-Virgin  Olive Oil",
    "Straße",
    "Œufs",
    "Salt_and_pepper",
    "日本酒",
    "ﬁne salt",
    "",
]

CLAUSES = ["", " , ; ", "minced", "Minced, room temperature; 100 g", "finely minced", "Large; beaten"]

DENSITY_NAMES = ["Canola oil", "Bread flour", "Honey", "Honeycrisp apples", "Sugar snap peas", "Pimentón", "", "!!!"]


def _bridge(value: dict[str, Any] | None):
    if value is None:
        return None
    match = PriceSource(
        id="bridge",
        normalized_name=normalized_name(value["name"]),
        measure_name=normalized_name(value["name"]),
        purchase_cost_cents=1,
    )
    return lambda source, target: _standard_volume_ratio(
        source, target, match, value["qualifier"]
    )


def _quantity(value) -> dict[str, Any] | None:
    return None if value is None else {"amount": value.amount, "unit": value.unit}


def _equivalency(value: dict[str, Any] | None) -> EquivalencyBasis | None:
    if value is None:
        return None
    return EquivalencyBasis(
        mass=Measure(*value["mass"]) if value["mass"] else None,
        volume=Measure(*value["volume"]) if value["volume"] else None,
        count=Measure(*value["count"]) if value["count"] else None,
        standard=value["standard"],
    )


def _hint_row(value: dict[str, Any]) -> SimpleNamespace:
    """An ingredient as ingredient_allergen_hints reads it, without a database."""
    catalog = (
        SimpleNamespace(
            allergen_defaults=SimpleNamespace(
                all=lambda: [
                    SimpleNamespace(allergen=key, status=status)
                    for key, status in value["catalog"].items()
                ]
            )
        )
        if value["catalog"] is not None
        else None
    )
    return SimpleNamespace(
        non_edible=value["nonEdible"],
        catalog_ingredient_id="catalog" if catalog is not None else None,
        catalog_ingredient=catalog,
        catalog_product_id=None,
        allergen_overrides=SimpleNamespace(
            all=lambda: [
                SimpleNamespace(allergen=key, status=status)
                for key, status in value["overrides"].items()
            ]
        ),
        nutrition_package_ingredients=value["package"],
    )


def _or_error(function, *args):
    try:
        return function(*args)
    except food_data.FoodDataError as error:
        return {"error": str(error)}


class ModelFreeParityFixtureTests(SimpleTestCase):
    """The fixtures that need no database."""

    def test_purchase_quantity_cases(self):
        cases = []
        for case in PURCHASES:
            expansion = purchase_quantity(
                case["amount"],
                case["unit"],
                _purchase_basis(case["source"]),
                PreparationBasis(
                    yield_percent=case["preparation"]["yieldPercent"],
                    conversion=tuple(
                        Measure(pair["amount"], pair["unit"])
                        for pair in case["preparation"]["conversion"]
                    ),
                    conversion_is_automatic=case["preparation"]["conversionIsAutomatic"],
                )
                if case["preparation"] is not None
                else None,
                standard_bridge=_bridge(case["bridge"]),
            )
            cases.append(
                {
                    **case,
                    "expect": {
                        "usage": _quantity(expansion.usage),
                        "purchase": _quantity(expansion.purchase),
                        "purchaseUnits": expansion.purchase_units,
                        "issues": [issue.code for issue in expansion.issues],
                    },
                }
            )
        batches = []
        for case in MEASURE_PAIRS:
            equivalency = _equivalency(case["equivalency"])
            batch = recipe_batch_basis(case["yieldAmount"], case["yieldUnit"], equivalency)
            batches.append(
                {
                    **case,
                    "expect": {
                        "pairs": [
                            {"amount": amount, "unit": unit}
                            for amount, unit in recipe_measure_pairs(
                                case["yieldAmount"], case["yieldUnit"], equivalency
                            )
                        ],
                        "grams": batch.grams,
                        "pieces": _quantity(batch.pieces),
                        "volume": _quantity(batch.volume),
                        "issues": [issue.code for issue in batch.issues],
                        "shares": [
                            {
                                "amount": amount,
                                "unit": unit,
                                "factor": share.factor,
                                "grams": share.grams,
                                "issues": [issue.code for issue in share.issues],
                            }
                            for amount, unit in SHARES
                            for share in [share_of_batch(amount, unit, batch)]
                        ],
                    },
                }
            )
        pin(
            self,
            "purchase-quantity-cases.json",
            {
                "purchaseQuantity": cases,
                "batches": batches,
                "normalizedName": [
                    {"input": name, "expect": normalized_name(name)} for name in NAMES
                ],
                "qualifierClauses": [
                    {"input": text, "expect": list(qualifier_clauses(text))} for text in CLAUSES
                ],
                "density": [
                    {
                        "milliliters": 236.5882365,
                        "name": name,
                        "qualifier": qualifier,
                        "allowStandard": allow,
                        "expect": grams_for(236.5882365, name, qualifier, allow_standard=allow),
                    }
                    for name in DENSITY_NAMES
                    for qualifier in ("", "sifted")
                    for allow in (True, False)
                ],
            },
        )

    def test_food_data_cases(self):
        searches = []
        for response in SEARCH_RESPONSES:
            with mock.patch.object(food_data, "_request", return_value={"foods": response["foods"]}):
                matches = food_data.search_foods(response["query"], scope=response["scope"])
            searches.append({**response, "expect": [match.as_json() for match in matches]})
        details = []
        for payload in DETAILS:
            with mock.patch.object(food_data, "_request", return_value=payload):
                result = _or_error(food_data.get_food, 1)
            details.append(
                {
                    "payload": payload,
                    "expect": result
                    if isinstance(result, dict)
                    else {
                        "description": result[0],
                        "per100g": result[1],
                        "packageIngredients": result[2],
                    },
                }
            )
        pin(
            self,
            "food-data-cases.json",
            {
                "nutritionPer100g": [
                    {"payload": food, "expect": _or_error(food_data.nutrition_per_100g, food)}
                    for food in FOODS
                ],
                "ranked": [
                    {
                        **ranking,
                        "expect": [
                            match.fdc_id
                            for match in food_data._ranked(
                                ranking["query"],
                                [
                                    food_data.FoodDataMatch(
                                        entry["fdcId"],
                                        entry["description"],
                                        entry["dataType"],
                                        entry["brand"],
                                    )
                                    for entry in ranking["matches"]
                                ],
                            )
                        ],
                    }
                    for ranking in RANKINGS
                ],
                "search": searches,
                "details": details,
                "labelNutritionPer100g": [
                    {
                        **label,
                        "expect": _or_error(
                            food_data.label_nutrition_per_100g,
                            label["values"],
                            label["servingGrams"],
                        ),
                    }
                    for label in LABELS
                ],
            },
        )

    def test_allergen_hints_cases(self):
        pin(
            self,
            "allergen-hints-cases.json",
            {
                "keywords": hints_module.KEYWORDS,
                "exclusions": hints_module.EXCLUSIONS,
                "allergenHints": [
                    {"text": text, "expect": hints_module.allergen_hints(text)}
                    for text in [*HINT_TEXTS, *KEYWORD_TEXTS]
                ],
                "ingredientAllergenHints": [
                    {
                        **entry,
                        "expect": hints_module.ingredient_allergen_hints(_hint_row(entry)),
                        "hasHints": hints_module.has_allergen_hints(_hint_row(entry)),
                    }
                    for entry in HINT_INGREDIENTS
                ],
            },
        )
