import { existsSync, readFileSync, writeFileSync } from "node:fs"

import { describe, expect, it } from "vitest"

import {
  analyzeRecipe,
  findIngredientProfile,
  inferRecipeCategory,
} from "@/lib/recipe/analyze"
import {
  buildFormula,
  canonicalFormulaName,
  classifyFormulaRole,
  compareFormulas,
  FORMULA_ROLE_LABELS,
  FORMULA_ROLES,
  gramOverrideKey,
  pastedFormulaInput,
  savedFormulaInput,
} from "@/lib/recipe/compare"
import { INGREDIENT_PROFILES } from "@/lib/recipe/data"
import { generalEnergyKcal, recipeNutritionFacts } from "@/lib/recipe/nutrition"
import { resolveNutritionIngredient } from "@/lib/recipe/parse"

/**
 * Formula compare and recipe analysis, pinned as data.
 *
 * `tests/fixtures/compare-cases.json` is copied verbatim into the Mac app
 * (`forkluck-macosTests/Fixtures/`), whose Swift ports of lib/recipe/compare.ts
 * and lib/recipe/analyze.ts assert every case. The inputs are every call
 * recipe-compare.test.ts and recipe-analysis.test.ts make, argument for
 * argument; each fixture entry names its arguments in the function's own
 * order. Regenerate with
 * `UPDATE_COMPARE_FIXTURE=1 pnpm exec vitest run tests/compare-cases.test.ts`
 * and copy it across.
 */

const FIXTURE = new URL("./fixtures/compare-cases.json", import.meta.url)
const GENERATOR =
  "cd apps/web && UPDATE_COMPARE_FIXTURE=1 pnpm exec vitest run tests/compare-cases.test.ts"

// The arguments of every call the two suites make, in the order they make them.
const CLASSIFY = [
  ["Bread flour"],
  ["Whole milk"],
  ["Warm water"],
  ["Unsalted butter"],
  ["Honey"],
  ["Fine sea salt"],
  ["Egg yolks"],
  ["3 large eggs"],
  ["Instant yeast"],
  ["Baking powder"],
  ["Tomatoes"],
  ["Almond flour"],
  ["Rye flour"],
  ["Cornstarch"],
  ["Buttermilk"],
  ["Heavy cream"],
  ["Milk powder"],
  ["Cream cheese"],
  ["Salted butter"],
  ["Coconut oil"],
  ["Brown sugar"],
  ["Maple syrup"],
  ["Baking soda"],
  ["Sourdough starter"],
  ["Egg whites"],
  ["Kosher salt"],
  ["Chocolate chips"],
  ["Vanilla extract"],
  ["Honey", true],
  ["Bread flour", true],
] as unknown as Parameters<typeof classifyFormulaRole>[]

const CANONICAL = [
  ["warm water"],
  ["Water"],
  ["eggs"],
  ["Whole egg"],
  ["Bread flour"],
  ["Whole Eggs"],
  ["large eggs"],
  ["Almond flours"],
  ["almond flour, sifted"],
  ["Rye flour"],
  ["Almond flour"],
] as unknown as Parameters<typeof canonicalFormulaName>[]

const BUILD = [
  [
    {
      key: "loaf",
      title: "loaf",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 500, written: "" },
        { id: "2", name: "Whole wheat flour", grams: 100, written: "" },
        { id: "3", name: "Water", grams: 400, written: "" },
        { id: "4", name: "Fine sea salt", grams: 12, written: "" },
        { id: "5", name: "Instant yeast", grams: 6, written: "" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "loaf",
      title: "loaf",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 500, written: "" },
        { id: "2", name: "Whole wheat flour", grams: 100, written: "" },
        { id: "3", name: "Water", grams: 400, written: "" },
        { id: "4", name: "Fine sea salt", grams: 12, written: "" },
        { id: "5", name: "Instant yeast", grams: 6, written: "" },
      ],
    },
    "weight",
  ],
  [
    {
      key: "g",
      title: "g",
      source: "saved",
      lines: [
        { id: "1", name: "Dark chocolate", grams: 200, written: "" },
        { id: "2", name: "Heavy cream", grams: 250, written: "", isBase: true },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "g",
      title: "g",
      source: "saved",
      lines: [
        { id: "1", name: "Dark chocolate", grams: 200, written: "" },
        { id: "2", name: "Heavy cream", grams: 250, written: "" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "g",
      title: "g",
      source: "saved",
      lines: [
        { id: "1", name: "Dark chocolate", grams: null, written: "1 cup" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "p",
      title: "p",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 500, written: "" },
        { id: "2", name: "Water", grams: null, written: "2 cups" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "p",
      title: "p",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 500, written: "" },
        { id: "2", name: "Water", grams: null, written: "2 cups" },
      ],
    },
    "bakers",
    { grams: { "p:2": 350 }, roles: {} },
  ],
  [
    {
      key: "c",
      title: "c",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 400, written: "" },
        { id: "2", name: "Almond flour", grams: 100, written: "" },
        { id: "3", name: "Water", grams: 300, written: "" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "c",
      title: "c",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 400, written: "" },
        { id: "2", name: "Almond flour", grams: 100, written: "" },
        { id: "3", name: "Water", grams: 300, written: "" },
      ],
    },
    "bakers",
    { grams: {}, roles: { "name:almond flour": "fat" } },
  ],
  [
    {
      key: "d",
      title: "d",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 300, written: "" },
        { id: "2", name: "bread flour", grams: 200, written: "" },
        { id: "3", name: "Water", grams: 350, written: "" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "d",
      title: "d",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 300, written: "" },
        { id: "2", name: "bread flour", grams: null, written: "2 cups" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "b",
      title: "b",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 500, written: "" },
        {
          id: "2",
          name: "Parchment",
          grams: 20,
          written: "",
          note: "nonEdible",
        },
        { id: "3", name: "Water", grams: 300, written: "", note: "discarded" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "f",
      title: "f",
      source: "saved",
      lines: [
        { id: "flour", name: "Bread flour", grams: 500, written: "" },
        { id: "water", name: "Warm water", grams: 380, written: "" },
        { id: "oil", name: "Extra virgin olive oil", grams: 40, written: "" },
        { id: "salt", name: "Fine sea salt", grams: 10, written: "" },
        { id: "yeast", name: "Instant yeast", grams: 5, written: "" },
        { id: "honey", name: "Honey", grams: 8, written: "" },
        { id: "tomatoes", name: "Cherry tomatoes", grams: 120, written: "" },
        { id: "rosemary", name: "Fresh rosemary", grams: 4, written: "" },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "m",
      title: "m",
      source: "saved",
      lines: [
        { id: "1", name: "Bread flour", grams: 500, written: "" },
        { id: "2", name: "Whole milk", grams: 200, written: "" },
        { id: "3", name: "Mystery powder", grams: 50, written: "" },
        {
          id: "4",
          name: "Filling",
          grams: 100,
          written: "",
          isComponent: true,
        },
      ],
    },
    "bakers",
  ],
  [
    {
      key: "rcp_old",
      title: "Old cookies",
      source: "saved",
      href: "/recipes/rcp_old/recipe",
      lines: [
        {
          id: "line-1",
          name: "Bread Flour",
          grams: 650,
          written: "650 g",
          isComponent: false,
          nutritionPer100g: null,
        },
        {
          id: "line-2",
          name: "Whole Eggs",
          grams: 200,
          written: "200 g",
          isComponent: false,
          nutritionPer100g: null,
        },
        {
          id: "line-3",
          name: "Kosher Salt",
          grams: 12,
          written: "12 g",
          isComponent: false,
          nutritionPer100g: null,
        },
      ],
    },
    "bakers",
  ],
] as unknown as Parameters<typeof buildFormula>[]

const COMPARE = [
  [
    [
      {
        key: "loaf",
        title: "loaf",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 500, written: "" },
          { id: "2", name: "Whole wheat flour", grams: 100, written: "" },
          { id: "3", name: "Water", grams: 400, written: "" },
          { id: "4", name: "Fine sea salt", grams: 12, written: "" },
          { id: "5", name: "Instant yeast", grams: 6, written: "" },
        ],
      },
      {
        key: "rich",
        title: "rich",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 500, written: "" },
          { id: "2", name: "Whole milk", grams: 300, written: "" },
          { id: "3", name: "Unsalted butter", grams: 100, written: "" },
          { id: "4", name: "Sugar", grams: 60, written: "" },
          { id: "5", name: "Egg", grams: 100, written: "" },
          { id: "6", name: "Fine sea salt", grams: 10, written: "" },
          { id: "7", name: "Instant yeast", grams: 7, written: "" },
        ],
      },
    ],
    "bakers",
  ],
  [
    [
      {
        key: "loaf",
        title: "loaf",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 500, written: "" },
          { id: "2", name: "Whole wheat flour", grams: 100, written: "" },
          { id: "3", name: "Water", grams: 400, written: "" },
          { id: "4", name: "Fine sea salt", grams: 12, written: "" },
          { id: "5", name: "Instant yeast", grams: 6, written: "" },
        ],
      },
      {
        key: "rich",
        title: "rich",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 500, written: "" },
          { id: "2", name: "Whole milk", grams: 300, written: "" },
          { id: "3", name: "Unsalted butter", grams: 100, written: "" },
          { id: "4", name: "Sugar", grams: 60, written: "" },
          { id: "5", name: "Egg", grams: 100, written: "" },
          { id: "6", name: "Fine sea salt", grams: 10, written: "" },
          { id: "7", name: "Instant yeast", grams: 7, written: "" },
        ],
      },
      {
        key: "loaf",
        title: "loaf",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 500, written: "" },
          { id: "2", name: "Whole wheat flour", grams: 100, written: "" },
          { id: "3", name: "Water", grams: 400, written: "" },
          { id: "4", name: "Fine sea salt", grams: 12, written: "" },
          { id: "5", name: "Instant yeast", grams: 6, written: "" },
        ],
      },
    ],
    "bakers",
  ],
  [
    [
      {
        key: "loaf",
        title: "loaf",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 500, written: "" },
          { id: "2", name: "Whole wheat flour", grams: 100, written: "" },
          { id: "3", name: "Water", grams: 400, written: "" },
          { id: "4", name: "Fine sea salt", grams: 12, written: "" },
          { id: "5", name: "Instant yeast", grams: 6, written: "" },
        ],
      },
    ],
    "bakers",
  ],
  [
    [
      {
        key: "loaf",
        title: "loaf",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 500, written: "" },
          { id: "2", name: "Whole wheat flour", grams: 100, written: "" },
          { id: "3", name: "Water", grams: 400, written: "" },
          { id: "4", name: "Fine sea salt", grams: 12, written: "" },
          { id: "5", name: "Instant yeast", grams: 6, written: "" },
        ],
      },
      {
        key: "p",
        title: "p",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 500, written: "" },
          { id: "2", name: "Water", grams: null, written: "2 cups" },
        ],
      },
    ],
    "bakers",
  ],
  [
    [
      {
        key: "a",
        title: "a",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 400, written: "" },
          { id: "2", name: "Almond flour", grams: 100, written: "" },
        ],
      },
      {
        key: "b",
        title: "b",
        source: "saved",
        lines: [
          { id: "1", name: "Bread flour", grams: 400, written: "" },
          { id: "2", name: "Almond flour", grams: 50, written: "" },
        ],
      },
    ],
    "bakers",
    { grams: {}, roles: { "name:almond flour": "fat" } },
  ],
  [[], "bakers"],
] as unknown as Parameters<typeof compareFormulas>[]

const SAVED = [
  [
    {
      publicId: "rcp_loaf",
      title: "Country loaf",
      items: [
        {
          kind: "header",
          position: 0,
          displayName: "Dough",
          quantity: null,
          unit: "",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "h",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "bread flour",
          quantity: 4,
          unit: "cup",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: true,
          excludedFromCost: false,
          ingredientId: "flour",
          subrecipeId: null,
          ingredientName: "Bread flour",
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "1",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "water",
          quantity: 250,
          unit: "g",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "2",
        },
        {
          kind: "subrecipe",
          position: 0,
          displayName: "Levain",
          quantity: 100,
          unit: "g",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: "levain",
          ingredientName: null,
          subrecipeName: "Levain",
          costCents: null,
          resolved: true,
          id: "3",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "parchment",
          quantity: 1,
          unit: "each",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: "parchment",
          subrecipeId: null,
          ingredientName: "Parchment",
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "4",
        },
        {
          kind: "note",
          position: 0,
          displayName: "Rest overnight",
          quantity: null,
          unit: "",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "n",
        },
      ],
    },
    {
      lines: [
        {
          kind: "ingredient",
          name: "",
          hasAllergenHints: false,
          ingredientPublicId: null,
          subrecipePublicId: null,
          linkedDescription: null,
          linkedSource: null,
          nonEdible: false,
          efficiencyAfterCooking: 100,
          grams: 500,
          netGrams: 500,
          status: "linked",
          itemId: "1",
        },
        {
          kind: "ingredient",
          name: "",
          hasAllergenHints: false,
          ingredientPublicId: null,
          subrecipePublicId: null,
          linkedDescription: null,
          linkedSource: null,
          nonEdible: false,
          efficiencyAfterCooking: 100,
          grams: null,
          netGrams: null,
          status: "unresolved",
          itemId: "2",
        },
        {
          kind: "subrecipe",
          name: "",
          hasAllergenHints: false,
          ingredientPublicId: null,
          subrecipePublicId: null,
          linkedDescription: null,
          linkedSource: null,
          nonEdible: false,
          efficiencyAfterCooking: 100,
          grams: 100,
          netGrams: 100,
          status: "linked",
          itemId: "3",
        },
        {
          kind: "ingredient",
          name: "",
          hasAllergenHints: false,
          ingredientPublicId: null,
          subrecipePublicId: null,
          linkedDescription: null,
          linkedSource: null,
          nonEdible: true,
          efficiencyAfterCooking: 100,
          grams: null,
          netGrams: null,
          status: "nonEdible",
          itemId: "4",
        },
      ],
    },
    [
      {
        id: "flour",
        normalizedName: "bread flour",
        purchaseCostCents: 100,
        name: "Bread flour",
        measureName: "Bread flour",
      },
    ],
  ],
  [
    {
      publicId: "rcp_old",
      title: "Old cookies",
      body: "650 g Bread Flour\n200 g Whole Eggs\n12 g Kosher Salt",
      items: [],
    },
    null,
    [],
  ],
  [
    {
      publicId: "rcp_old",
      title: "Old cookies",
      body: "650 g Bread Flour\n200 g Whole Eggs\n12 g Kosher Salt",
      items: [
        {
          kind: "header",
          position: 0,
          displayName: "Dough",
          quantity: null,
          unit: "",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "h",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "bread flour",
          quantity: 4,
          unit: "cup",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: true,
          excludedFromCost: false,
          ingredientId: "flour",
          subrecipeId: null,
          ingredientName: "Bread flour",
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "1",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "water",
          quantity: 250,
          unit: "g",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "2",
        },
        {
          kind: "subrecipe",
          position: 0,
          displayName: "Levain",
          quantity: 100,
          unit: "g",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: "levain",
          ingredientName: null,
          subrecipeName: "Levain",
          costCents: null,
          resolved: true,
          id: "3",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "parchment",
          quantity: 1,
          unit: "each",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: "parchment",
          subrecipeId: null,
          ingredientName: "Parchment",
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "4",
        },
        {
          kind: "note",
          position: 0,
          displayName: "Rest overnight",
          quantity: null,
          unit: "",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "n",
        },
      ],
    },
    null,
    [],
  ],
  [
    {
      publicId: "rcp_loaf",
      title: "Country loaf",
      items: [
        {
          kind: "header",
          position: 0,
          displayName: "Dough",
          quantity: null,
          unit: "",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "h",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "bread flour",
          quantity: 4,
          unit: "cup",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: true,
          excludedFromCost: false,
          ingredientId: "flour",
          subrecipeId: null,
          ingredientName: "Bread flour",
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "1",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "water",
          quantity: 250,
          unit: "g",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "2",
        },
        {
          kind: "subrecipe",
          position: 0,
          displayName: "Levain",
          quantity: 100,
          unit: "g",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: "levain",
          ingredientName: null,
          subrecipeName: "Levain",
          costCents: null,
          resolved: true,
          id: "3",
        },
        {
          kind: "ingredient",
          position: 0,
          displayName: "parchment",
          quantity: 1,
          unit: "each",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: "parchment",
          subrecipeId: null,
          ingredientName: "Parchment",
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "4",
        },
        {
          kind: "note",
          position: 0,
          displayName: "Rest overnight",
          quantity: null,
          unit: "",
          preparationNote: "",
          efficiency: 100,
          efficiencyAfterCooking: 100,
          isBase: false,
          excludedFromCost: false,
          ingredientId: null,
          subrecipeId: null,
          ingredientName: null,
          subrecipeName: null,
          costCents: null,
          resolved: true,
          id: "n",
        },
      ],
    },
    null,
    [],
  ],
] as unknown as Parameters<typeof savedFormulaInput>[]

const PASTED = [
  [
    "paste:1",
    "",
    "# Serious brioche\n500 g bread flour\n3 large eggs\n2 cups water\n1 cup unsalted butter\n1/2 cup buttermilk\n10 g salt\nMix everything and rest.",
    [
      {
        id: "egg",
        normalizedName: "egg",
        purchaseCostCents: 100,
        name: "Egg",
        measureName: "Egg",
      },
      {
        id: "water",
        normalizedName: "water",
        purchaseCostCents: 100,
        name: "Water",
        measureName: "Water",
      },
      {
        id: "butter",
        normalizedName: "unsalted butter",
        purchaseCostCents: 100,
        name: "Unsalted butter",
        measureName: "Unsalted butter",
        conversion: {
          usesStandardConversion: false,
          weight: { amount: 227, unit: "g" },
          volume: { amount: 1, unit: "cup" },
          each: null,
        },
      },
    ],
  ],
  [
    "paste:3",
    "",
    "4 whole eggs\n",
    [
      {
        id: "egg",
        normalizedName: "whole egg",
        purchaseCostCents: 100,
        name: "Whole egg",
        measureName: "Whole egg",
        conversion: {
          usesStandardConversion: false,
          weight: { amount: 62, unit: "g" },
          volume: null,
          each: { amount: 1, unit: "pcs" },
        },
      },
    ],
  ],
  [
    "paste:5",
    "",
    "4 eggs\n",
    [
      {
        id: "egg",
        normalizedName: "egg",
        purchaseCostCents: 100,
        name: "Egg",
        measureName: "Egg",
        conversion: {
          usesStandardConversion: false,
          weight: { amount: 62, unit: "g" },
          volume: null,
          each: { amount: 1, unit: "pcs" },
        },
      },
    ],
  ],
  ["paste:4", "", "4 widgets\n", []],
  [
    "paste:6",
    "",
    "30 g bourbon\n",
    [
      {
        id: "bourbon",
        normalizedName: "bourbon whiskey",
        purchaseCostCents: 100,
        name: "Bourbon whiskey",
        measureName: "Bourbon whiskey",
      },
    ],
  ],
  [
    "paste:7",
    "",
    "30 g bourbon\n",
    [
      {
        id: "bourbon",
        normalizedName: "bourbon whiskey",
        purchaseCostCents: 100,
        name: "Bourbon whiskey",
        measureName: "Bourbon whiskey",
      },
    ],
    [{ line: "bourbon", targetId: "bourbon", targetName: "Bourbon whiskey" }],
  ],
  [
    "paste:2",
    "From the book",
    "500 g flour\n3 to 4 cups of who knows\n1,5 kg sugar",
    [],
  ],
  ["paste:3", "  ", "500 g flour", []],
] as unknown as Parameters<typeof pastedFormulaInput>[]

const ANALYZE = [
  [[{ id: "sugar", name: "sugar", grams: 100 }]],
  [[{ id: "sugar", name: "granulated sugar", grams: 100 }]],
  [[{ id: "sugar", name: "white sugar", grams: 100 }]],
  [[{ id: "sugar", name: "caster sugar", grams: 100 }]],
  [
    [
      { id: "flour", name: "Bread flour", grams: 500 },
      { id: "water", name: "Warm water", grams: 380 },
      { id: "oil", name: "Extra virgin olive oil", grams: 40 },
      { id: "salt", name: "Fine sea salt", grams: 10 },
      { id: "yeast", name: "Instant yeast", grams: 5 },
      { id: "honey", name: "Honey", grams: 8 },
      { id: "tomatoes", name: "Cherry tomatoes", grams: 120 },
      { id: "rosemary", name: "Fresh rosemary", grams: 4 },
    ],
  ],
  [
    [
      { id: "flour", name: "Stoneground plain flour", grams: 100 },
      { id: "water", name: "Warm water (38 C)", grams: 60 },
    ],
  ],
  [
    [
      {
        id: "butter",
        name: "Butter",
        grams: 200,
        nutritionPer100g: {
          water: 16,
          fat: 81,
          protein: 1,
          sugars: 0,
          starch: 0,
          fiber: 0,
          salt: 0,
          other: 2,
          totalCarbohydrate: 0,
          sodiumMg: 11,
          saturatedFat: 51,
        },
      },
    ],
  ],
  [[{ id: "oil", name: "Olive oil", grams: 200 }]],
  [[{ id: "flour", name: "Bread flour", grams: 100 }]],
  [
    [
      { id: "flour", name: "Bread flour", grams: 100 },
      { id: "mystery", name: "Moon dust", grams: 50 },
    ],
  ],
  [
    [
      { id: "flour", name: "Bread flour", grams: 100 },
      { id: "water", name: "Water", grams: 70 },
      { id: "salt", name: "Salt", grams: 2 },
    ],
    "bread",
  ],
  [
    [
      { id: "flour", name: "Bread flour", grams: 100 },
      { id: "water", name: "Water", grams: 70 },
      { id: "salt", name: "Salt", grams: 3 },
    ],
    "bread",
  ],
  [
    [
      { id: "flour", name: "Bread flour", grams: 100 },
      { id: "water", name: "Water", grams: 70 },
      { id: "salt", name: "Salt", grams: 2.54 },
    ],
    "bread",
  ],
  [
    [
      { id: "flour", name: "Bread flour", grams: 100 },
      { id: "water", name: "Water", grams: 70 },
      { id: "salt", name: "Salt", grams: 5 },
    ],
    "bread",
  ],
  [
    [
      { id: "flour", name: "Bread flour", grams: 100 },
      { id: "water", name: "Water", grams: 70 },
      { id: "sugar", name: "Granulated sugar", grams: 10 },
    ],
    "bread",
  ],
  [
    [
      { id: "flour", name: "All-purpose flour", grams: 100 },
      { id: "water", name: "Water", grams: 60 },
      { id: "butter", name: "Butter", grams: 80 },
      { id: "sugar", name: "Sugar", grams: 100 },
      { id: "salt", name: "Salt", grams: 1 },
    ],
    "cake",
  ],
  [
    [
      { id: "flour", name: "All-purpose flour", grams: 100 },
      { id: "water", name: "Water", grams: 200 },
      { id: "butter", name: "Butter", grams: 200 },
      { id: "sugar", name: "Sugar", grams: 200 },
      { id: "salt", name: "Salt", grams: 3 },
    ],
    "cake",
  ],
  [
    [
      { id: "flour", name: "All-purpose flour", grams: 100 },
      { id: "water", name: "Water", grams: 70 },
    ],
    "general",
  ],
  [[], "bread"],
  [
    [
      {
        id: "mapped",
        name: "Mapped formula",
        grams: 100,
        nutritionPer100g: {
          water: 12,
          fat: 29.847,
          protein: 4.932,
          sugars: 18.28,
          starch: 33.022,
          fiber: 1.209,
          salt: 0.629,
          other: 0,
          totalCarbohydrate: 52.51,
          sodiumMg: 251.7,
        },
      },
    ],
  ],
  [
    [
      {
        id: "mapped",
        name: "Mapped food",
        grams: 100,
        nutritionPer100g: {
          water: 50,
          fat: 10,
          protein: 10,
          sugars: 5,
          starch: 15,
          fiber: 5,
          salt: 1,
          other: 4,
        },
      },
    ],
  ],
  [
    [
      { id: "sugar", name: "Granulated sugar", grams: 100 },
      { id: "water", name: "Water", grams: 100 },
    ],
  ],
  [[{ id: "sugar", name: "Granulated sugar", grams: 200 }]],
  [
    [
      { id: "paste-1", name: "Bread Flour", grams: 500 },
      { id: "paste-2", name: "Warm Water", grams: 380 },
      { id: "paste-3", name: "Extra Virgin Olive Oil", grams: 40 },
      { id: "paste-4", name: "Fine Sea Salt", grams: 10 },
      { id: "paste-5", name: "Instant Yeast", grams: 5 },
      { id: "paste-6", name: "Honey", grams: 8 },
      { id: "paste-7", name: "Cherry Tomatoes", grams: 120 },
      { id: "paste-8", name: "Fresh Rosemary", grams: 4 },
    ],
    "bread",
  ],
  [
    [
      { id: "sugar", name: "Granulated sugar", grams: 100 },
      { id: "mystery", name: "Mystery powder", grams: 100 },
    ],
  ],
  [
    [
      { id: "water-dough", name: "Mooncake water dough", grams: 165 },
      { id: "oil-dough", name: "Mooncake oil dough", grams: 330 },
      { id: "scallions", name: "Scallions", grams: 600 },
      { id: "pork", name: "Ground pork", grams: 200 },
      { id: "pepper", name: "Black pepper", grams: 8 },
      { id: "salt", name: "Salt", grams: 10 },
    ],
  ],
  [
    [
      {
        id: "pork",
        name: "Ground pork",
        grams: 100,
        nutritionPer100g: {
          water: 60,
          fat: 20,
          protein: 19,
          sugars: 0,
          starch: 0,
          fiber: 0,
          salt: 1,
          other: 0,
        },
      },
    ],
  ],
  [[{ id: "mystery", name: "Mystery powder", grams: 100 }]],
  [[{ id: "paste-1", name: "Granulated sugar", grams: 100 }]],
  [
    [
      {
        id: "l1",
        name: "Olive Oil",
        isComponent: false,
        nutritionPer100g: null,
        grams: 100,
      },
    ],
  ],
  [[{ id: "l1", name: "Butter", grams: 100 }]],
  [
    [
      {
        id: "l1",
        name: "Flour",
        isComponent: false,
        nutritionPer100g: null,
        grams: 100,
      },
    ],
  ],
  [[{ id: "l1", name: "House Flour", grams: 100 }]],
  [
    [
      {
        id: "l1",
        name: "Honey",
        isComponent: true,
        nutritionPer100g: null,
        grams: 100,
      },
    ],
  ],
  [[{ id: "l1", name: "Honey", grams: 100 }]],
  [
    [
      { id: "sugar", name: "Granulated sugar", grams: 1000 },
      { id: "mystery", name: "Mystery powder", grams: 0.4 },
    ],
  ],
] as unknown as Parameters<typeof analyzeRecipe>[]

const PROFILES = [
  ["sugar"],
  ["granulated sugar"],
  ["white sugar"],
  ["caster sugar"],
  ["2 cups (sifted) STRONG-BREAD FLOUR"],
  ["extra-virgin olive oil"],
  ["0.5 kg sugar"],
  ["1/2 cup sugar"],
  ["tomato paste"],
  ["milk powder"],
  ["milk (skim)"],
  ["egg noodles"],
  ["Salted butter"],
  ["Unsalted butter"],
  ["Butter"],
  ["Olive Oil"],
  ["House Flour"],
  ["Flour"],
  ["All-purpose flour"],
  ["Honey"],
  ["Bread Flour"],
  ["Warm Water"],
  ["Extra Virgin Olive Oil"],
  ["Fine Sea Salt"],
  ["Instant Yeast"],
  ["Cherry Tomatoes"],
  ["Fresh Rosemary"],
] as unknown as Parameters<typeof findIngredientProfile>[]

const CATEGORIES = [
  [
    [
      { id: "flour", name: "Bread flour", grams: 100 },
      { id: "yeast", name: "Instant yeast", grams: 1 },
    ],
  ],
  [
    [
      { id: "flour", name: "All-purpose flour", grams: 100 },
      { id: "leavener", name: "Baking powder", grams: 4 },
    ],
  ],
  [
    [
      { id: "flour", name: "All-purpose flour", grams: 100 },
      { id: "egg", name: "Eggs", grams: 50 },
      { id: "fat", name: "Butter", grams: 70 },
      { id: "sugar", name: "Sugar", grams: 100 },
    ],
  ],
  [
    [
      { id: "tomato", name: "Tomatoes", grams: 100 },
      { id: "oil", name: "Olive oil", grams: 10 },
    ],
  ],
] as unknown as Parameters<typeof inferRecipeCategory>[]

const FACTS = [
  [
    {
      totalMassG: 100,
      knownMassG: 100,
      coveragePercent: 100,
      waterG: 12,
      waterPercent: 12,
      dryMatterG: 87.9,
      dryMatterPercent: 88,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 33,
          percentOfDryMatter: 37.6,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 4.9,
          percentOfDryMatter: 5.6,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 29.8,
          percentOfDryMatter: 33.9,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 1.2,
          percentOfDryMatter: 1.4,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 18.3,
          percentOfDryMatter: 20.8,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0.6,
          percentOfDryMatter: 0.7,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 12,
        fat: 29.847,
        protein: 4.932,
        sugars: 18.28,
        starch: 33.022,
        fiber: 1.209,
        salt: 0.629,
        other: 0,
        totalCarbohydrate: 52.51,
        sodiumMg: 251.7,
        saturatedFat: 0,
      },
      per100g: {
        water: 12,
        dryMatter: 87.9,
        fat: 29.8,
        protein: 4.9,
        sugars: 18.3,
        starch: 33,
        fiber: 1.2,
        salt: 0.6,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "mapped",
          inputName: "Mapped formula",
          canonicalName: "Mapped formula",
          grams: 100,
          profileKey: "mapped:mapped",
        },
      ],
      unknownIngredients: [],
      caveats: [
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
  ],
  [
    {
      totalMassG: 200,
      knownMassG: 200,
      coveragePercent: 100,
      waterG: 100,
      waterPercent: 50,
      dryMatterG: 100,
      dryMatterPercent: 50,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 100,
          percentOfDryMatter: 100,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 100,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 100,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 50,
        dryMatter: 50,
        fat: 0,
        protein: 0,
        sugars: 50,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "sugar",
          inputName: "Granulated sugar",
          canonicalName: "Sugar",
          grams: 100,
          profileKey: "granulated-sugar",
        },
        {
          id: "water",
          inputName: "Water",
          canonicalName: "Water",
          grams: 100,
          profileKey: "water",
        },
      ],
      unknownIngredients: [],
      caveats: [
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
  ],
  [
    {
      totalMassG: 200,
      knownMassG: 200,
      coveragePercent: 100,
      waterG: 100,
      waterPercent: 50,
      dryMatterG: 100,
      dryMatterPercent: 50,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 100,
          percentOfDryMatter: 100,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 100,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 100,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 50,
        dryMatter: 50,
        fat: 0,
        protein: 0,
        sugars: 50,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "sugar",
          inputName: "Granulated sugar",
          canonicalName: "Sugar",
          grams: 100,
          profileKey: "granulated-sugar",
        },
        {
          id: "water",
          inputName: "Water",
          canonicalName: "Water",
          grams: 100,
          profileKey: "water",
        },
      ],
      unknownIngredients: [],
      caveats: [
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
    { finishedWeightG: 150 },
  ],
  [
    {
      totalMassG: 200,
      knownMassG: 200,
      coveragePercent: 100,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 200,
      dryMatterPercent: 100,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 200,
          percentOfDryMatter: 100,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 200,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 200,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 100,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "sugar",
          inputName: "Granulated sugar",
          canonicalName: "Sugar",
          grams: 200,
          profileKey: "granulated-sugar",
        },
      ],
      unknownIngredients: [],
      caveats: [
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
  ],
  [
    {
      totalMassG: 200,
      knownMassG: 200,
      coveragePercent: 100,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 200,
      dryMatterPercent: 100,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 200,
          percentOfDryMatter: 100,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 200,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 200,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 100,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "sugar",
          inputName: "Granulated sugar",
          canonicalName: "Sugar",
          grams: 200,
          profileKey: "granulated-sugar",
        },
      ],
      unknownIngredients: [],
      caveats: [
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
    { portions: 4 },
  ],
  [
    {
      totalMassG: 200,
      knownMassG: 100,
      coveragePercent: 50,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 100,
      dryMatterPercent: 100,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 100,
          percentOfDryMatter: 100,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 100,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 100,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "sugar",
          inputName: "Granulated sugar",
          canonicalName: "Sugar",
          grams: 100,
          profileKey: "granulated-sugar",
        },
      ],
      unknownIngredients: [
        { id: "mystery", name: "Mystery powder", grams: 100 },
      ],
      caveats: [
        "1 ingredient is excluded from composition until mapped.",
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
  ],
  [
    {
      totalMassG: 1313,
      knownMassG: 10,
      coveragePercent: 0.8,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 10,
      dryMatterPercent: 100,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 10,
          percentOfDryMatter: 100,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 0,
        starch: 0,
        fiber: 0,
        salt: 10,
        other: 0,
        totalCarbohydrate: 0,
        sodiumMg: 4000,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 100,
        fat: 0,
        protein: 0,
        sugars: 0,
        starch: 0,
        fiber: 0,
        salt: 100,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "salt",
          inputName: "Salt",
          canonicalName: "Fine sea salt",
          grams: 10,
          profileKey: "sea-salt",
        },
      ],
      unknownIngredients: [
        { id: "water-dough", name: "Mooncake water dough", grams: 165 },
        { id: "oil-dough", name: "Mooncake oil dough", grams: 330 },
        { id: "scallions", name: "Scallions", grams: 600 },
        { id: "pork", name: "Ground pork", grams: 200 },
        { id: "pepper", name: "Black pepper", grams: 8 },
      ],
      caveats: [
        "5 ingredients are excluded from composition until mapped.",
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
    { portions: 11 },
  ],
  [
    {
      totalMassG: 100,
      knownMassG: 100,
      coveragePercent: 100,
      waterG: 60,
      waterPercent: 60,
      dryMatterG: 40,
      dryMatterPercent: 40,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 19,
          percentOfDryMatter: 47.5,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 20,
          percentOfDryMatter: 50,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 1,
          percentOfDryMatter: 2.5,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 60,
        fat: 20,
        protein: 19,
        sugars: 0,
        starch: 0,
        fiber: 0,
        salt: 1,
        other: 0,
        totalCarbohydrate: 0,
        sodiumMg: 400,
        saturatedFat: 0,
      },
      per100g: {
        water: 60,
        dryMatter: 40,
        fat: 20,
        protein: 19,
        sugars: 0,
        starch: 0,
        fiber: 0,
        salt: 1,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "pork",
          inputName: "Ground pork",
          canonicalName: "Ground pork",
          grams: 100,
          profileKey: "mapped:pork",
        },
      ],
      unknownIngredients: [],
      caveats: [
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
  ],
  [
    {
      totalMassG: 100,
      knownMassG: 0,
      coveragePercent: 0,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 0,
      dryMatterPercent: 0,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 0,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 0,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 0,
        fat: 0,
        protein: 0,
        sugars: 0,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [],
      unknownIngredients: [
        { id: "mystery", name: "Mystery powder", grams: 100 },
      ],
      caveats: [
        "1 ingredient is excluded from composition until mapped.",
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
    { portions: 2 },
  ],
  [
    {
      totalMassG: 100,
      knownMassG: 100,
      coveragePercent: 100,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 100,
      dryMatterPercent: 100,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 100,
          percentOfDryMatter: 100,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 100,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 100,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "paste-1",
          inputName: "Granulated sugar",
          canonicalName: "Sugar",
          grams: 100,
          profileKey: "granulated-sugar",
        },
      ],
      unknownIngredients: [],
      caveats: [
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
    { unweighedIngredientCount: 1 },
  ],
  [
    {
      totalMassG: 200,
      knownMassG: 100,
      coveragePercent: 50,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 100,
      dryMatterPercent: 100,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 100,
          percentOfDryMatter: 100,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 100,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 100,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "sugar",
          inputName: "Granulated sugar",
          canonicalName: "Sugar",
          grams: 100,
          profileKey: "granulated-sugar",
        },
      ],
      unknownIngredients: [
        { id: "mystery", name: "Mystery powder", grams: 100 },
      ],
      caveats: [
        "1 ingredient is excluded from composition until mapped.",
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
    { unweighedIngredientCount: 1 },
  ],
  [
    {
      totalMassG: 100,
      knownMassG: 0,
      coveragePercent: 0,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 0,
      dryMatterPercent: 0,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 0,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 0,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 0,
        fat: 0,
        protein: 0,
        sugars: 0,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [],
      unknownIngredients: [{ id: "l1", name: "Honey", grams: 100 }],
      caveats: [
        "1 ingredient is excluded from composition until mapped.",
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
  ],
  [
    {
      totalMassG: 1000.4,
      knownMassG: 1000,
      coveragePercent: 100,
      waterG: 0,
      waterPercent: 0,
      dryMatterG: 1000,
      dryMatterPercent: 100,
      flourMassG: 0,
      solids: [
        {
          key: "starch",
          label: "Starch",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#18181b",
        },
        {
          key: "protein",
          label: "Protein",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#3f3f46",
        },
        {
          key: "fat",
          label: "Fat",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#52525b",
        },
        {
          key: "fiber",
          label: "Fiber",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#71717a",
        },
        {
          key: "sugars",
          label: "Sugars",
          grams: 1000,
          percentOfDryMatter: 100,
          color: "#a1a1aa",
        },
        {
          key: "salt",
          label: "Salt",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#d4d4d8",
        },
        {
          key: "other",
          label: "Other",
          grams: 0,
          percentOfDryMatter: 0,
          color: "#e4e4e7",
        },
      ],
      nutritionTotals: {
        water: 0,
        fat: 0,
        protein: 0,
        sugars: 1000,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
        totalCarbohydrate: 1000,
        sodiumMg: 0,
        saturatedFat: 0,
      },
      per100g: {
        water: 0,
        dryMatter: 100,
        fat: 0,
        protein: 0,
        sugars: 100,
        starch: 0,
        fiber: 0,
        salt: 0,
        other: 0,
      },
      signals: [
        {
          key: "hydration",
          label: "Hydration",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "fat",
          label: "Fat",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "sugar",
          label: "Sweetener",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
        {
          key: "salt",
          label: "Salt",
          value: null,
          unit: "",
          status: "unknown",
          position: 0,
          scaleMin: 0,
          scaleMax: 100,
          targetMin: 0,
          targetMax: 0,
          targetStart: 0,
          targetEnd: 0,
          summary: "No benchmark",
          basis:
            "Formulation ranges are currently available for bread, dough, cake, and batter only.",
        },
      ],
      matchedIngredients: [
        {
          id: "sugar",
          inputName: "Granulated sugar",
          canonicalName: "Sugar",
          grams: 1000,
          profileKey: "granulated-sugar",
        },
      ],
      unknownIngredients: [
        { id: "mystery", name: "Mystery powder", grams: 0.4 },
      ],
      caveats: [
        "1 ingredient is excluded from composition until mapped.",
        "This is a raw-batch formulation estimate; fermentation, evaporation, cooking loss, and final yield are not modeled.",
        "Seed ingredient values are representative and are not a substitute for a verified nutrient database.",
      ],
    },
  ],
] as unknown as Parameters<typeof recipeNutritionFacts>[]

const ENERGY = [
  [{ protein: 10, carbohydrate: 20, fat: 5, fiber: 3 }],
] as unknown as Parameters<typeof generalEnergyKcal>[]

const NUTRITION_IDENTITY = [
  [
    "Butter",
    [
      {
        id: "olive",
        name: "Olive Oil",
        normalizedName: "olive oil",
        source: "pantry",
      },
    ],
    [
      {
        line: "Butter",
        targetId: "olive",
        targetName: "Olive Oil",
        measureName: "Olive Oil",
        targetKind: "ingredient",
      },
    ],
  ],
  [
    "House Flour",
    [
      {
        id: "flour",
        name: "House Flour",
        normalizedName: "house flour",
        measureName: "Flour",
        source: "pantry",
      },
    ],
  ],
  [
    "House Flour",
    [
      {
        id: "dough",
        name: "House Flour",
        normalizedName: "house flour",
        measureName: "Flour",
        source: "component",
      },
    ],
  ],
  [
    "Honey",
    [
      {
        id: "honey-glaze",
        name: "Honey",
        normalizedName: "honey",
        source: "component",
      },
    ],
  ],
] as unknown as Parameters<typeof resolveNutritionIngredient>[]

/** Undefined arguments read as null in the fixture. */
const orNull = <T>(value: T | undefined) => (value === undefined ? null : value)

function generate() {
  return {
    generator: GENERATOR,
    constants: {
      formulaRoles: FORMULA_ROLES,
      formulaRoleLabels: FORMULA_ROLE_LABELS,
      ingredientProfiles: INGREDIENT_PROFILES,
    },
    classifyFormulaRole: CLASSIFY.map(([name, isComponent]) => ({
      name,
      isComponent: isComponent ?? false,
      expect: classifyFormulaRole(name, isComponent),
    })),
    canonicalFormulaName: CANONICAL.map(([name]) => ({
      name,
      expect: canonicalFormulaName(name),
    })),
    gramOverrideKey: [["rcp_a", "line-1"]].map(([formulaKey, lineId]) => ({
      formulaKey,
      lineId,
      expect: gramOverrideKey(formulaKey, lineId),
    })),
    buildFormula: BUILD.map(([input, mode, overrides]) => ({
      input,
      mode,
      overrides: orNull(overrides),
      expect: buildFormula(input, mode, overrides),
    })),
    compareFormulas: COMPARE.map(([inputs, mode, overrides]) => ({
      inputs,
      mode,
      overrides: orNull(overrides),
      expect: compareFormulas(inputs, mode, overrides),
    })),
    savedFormulaInput: SAVED.map(([recipe, nutrition, identities]) => ({
      recipe,
      nutrition,
      identities,
      expect: savedFormulaInput(recipe, nutrition, identities),
    })),
    pastedFormulaInput: PASTED.map(
      ([key, title, text, identities, matches]) => ({
        key,
        title,
        text,
        identities,
        matches: orNull(matches),
        expect: pastedFormulaInput(key, title, text, identities, matches),
      })
    ),
    analyzeRecipe: ANALYZE.map(([ingredients, category]) => ({
      ingredients,
      category: orNull(category),
      expect: analyzeRecipe(ingredients, category),
    })),
    findIngredientProfile: PROFILES.map(([name]) => ({
      name,
      expect: findIngredientProfile(name),
    })),
    inferRecipeCategory: CATEGORIES.map(([ingredients]) => ({
      ingredients,
      expect: inferRecipeCategory(ingredients),
    })),
    recipeNutritionFacts: FACTS.map(([analysis, basis]) => ({
      analysis,
      basis: orNull(basis),
      expect: recipeNutritionFacts(analysis, basis),
    })),
    generalEnergyKcal: ENERGY.map(([macros]) => ({
      macros,
      expect: generalEnergyKcal(macros),
    })),
    resolveNutritionIngredient: NUTRITION_IDENTITY.map(
      ([name, identities, matches]) => ({
        name,
        identities: orNull(identities),
        matches: orNull(matches),
        expect: resolveNutritionIngredient(name, identities, matches),
      })
    ),
  }
}

describe("the compare fixture the Mac app asserts against", () => {
  it("matches what compare and analysis compute", () => {
    const generated = JSON.parse(JSON.stringify(generate()))
    if (process.env.UPDATE_COMPARE_FIXTURE || !existsSync(FIXTURE)) {
      writeFileSync(FIXTURE, JSON.stringify(generated, null, 2) + "\n")
    }
    const committed = JSON.parse(readFileSync(FIXTURE, "utf8"))
    expect(committed).toEqual(generated)
  })
})
