# Generated by Django 5.2.16 on 2026-08-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrition_package_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition_package_unit',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('nutrition_package_amount__isnull', True), ('nutrition_package_amount__gt', 0), _connector='OR'), name='recipe_nutrition_package_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('nutrition_package_amount__isnull', True), models.Q(('nutrition_package_unit', ''), _negated=True), _connector='OR'), name='recipe_nutrition_package_pair'),
        ),
    ]
