# Generated by Django 5.2.16 on 2026-08-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forkluck", "0007_manual_sales_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="benchcostsettings",
            name="payroll_tax_bps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="benchcostsettings",
            name="unpaid_break_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="benchcostsettings",
            name="unpaid_break_per_hours",
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="unpaid_break_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unpaid_break_seconds__lte", models.F("paid_seconds"))
                ),
                name="time_entry_unpaid_break_within_paid",
            ),
        ),
    ]
