# Generated by Django 5.2.16 on 2026-08-29 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forkluck', '0009_salesproduct_base_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesChannelListing',
            new_name='SalesProductVariant',
        ),
        migrations.RenameModel(
            old_name='SalesListingMember',
            new_name='SalesVariantMember',
        ),
        migrations.RemoveConstraint(
            model_name='salesproductvariant',
            name='sales_listing_scoped_match_unique',
        ),
        migrations.RemoveConstraint(
            model_name='salesproductvariant',
            name='sales_listing_multiplier_positive',
        ),
        migrations.RemoveConstraint(
            model_name='salesproductvariant',
            name='sales_listing_kind_product_shape',
        ),
        migrations.RemoveConstraint(
            model_name='salesproductvariant',
            name='sales_listing_modifier_not_assorted',
        ),
        migrations.RemoveConstraint(
            model_name='salesproductvariant',
            name='sales_listing_attribution_percent_range',
        ),
        migrations.RemoveConstraint(
            model_name='salesproductvariant',
            name='sales_listing_one_manual_product',
        ),
        migrations.RemoveConstraint(
            model_name='salesvariantmember',
            name='sales_listing_member_unique',
        ),
        migrations.RemoveConstraint(
            model_name='salesvariantmember',
            name='sales_listing_member_quantity_positive',
        ),
        migrations.RenameIndex(
            model_name='salesproductvariant',
            new_name='forkluck_sa_user_id_409c8d_idx',
            old_name='forkluck_sa_user_id_ac2eb0_idx',
        ),
        migrations.AlterField(
            model_name='salesproductvariant',
            name='created_by_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variants', to='forkluck.salesimport'),
        ),
        migrations.AlterField(
            model_name='salesproductvariant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='forkluck.salesproduct'),
        ),
        migrations.AlterField(
            model_name='salesproductvariant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_product_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='salesproductvariant',
            constraint=models.UniqueConstraint(fields=('user', 'channel', 'provider_account_id', 'match_key'), name='sales_variant_scoped_match_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesproductvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'manual'), ('product__isnull', False)), fields=('user', 'product'), name='sales_variant_one_manual_product'),
        ),
        migrations.AddConstraint(
            model_name='salesproductvariant',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_multiplier__gt', 0)), name='sales_variant_multiplier_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesproductvariant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'assorted'), ('product__isnull', True)), models.Q(('kind', 'direct'), ('product__isnull', False)), _connector='OR'), name='sales_variant_kind_product_shape'),
        ),
        migrations.AddConstraint(
            model_name='salesproductvariant',
            constraint=models.CheckConstraint(condition=models.Q(('identity_kind', 'modifier'), ('kind', 'assorted'), _negated=True), name='sales_variant_modifier_not_assorted'),
        ),
        migrations.AddConstraint(
            model_name='salesproductvariant',
            constraint=models.CheckConstraint(condition=models.Q(('attribution_percent__isnull', True), models.Q(('attribution_percent__gte', 0), ('attribution_percent__lte', 100)), _connector='OR'), name='sales_variant_attribution_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='salesvariantmember',
            constraint=models.UniqueConstraint(fields=('listing', 'product'), name='sales_variant_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesvariantmember',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='sales_variant_member_quantity_positive'),
        ),
    ]
