# Generated by Django 5.2.16 on 2026-08-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0010_rename_listing_models_to_variants'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesvariantmember',
            name='sales_variant_member_unique',
        ),
        migrations.RemoveIndex(
            model_name='saleslinemodifier',
            name='forkluck_sa_listing_5abe8a_idx',
        ),
        migrations.RenameField(
            model_name='salescatalogitem',
            old_name='variant_name',
            new_name='external_variant_title',
        ),
        migrations.RenameField(
            model_name='salesline',
            old_name='variant_name',
            new_name='external_variant_title',
        ),
        migrations.RenameField(
            model_name='salesline',
            old_name='listing',
            new_name='variant',
        ),
        migrations.RenameField(
            model_name='saleslinemodifier',
            old_name='listing',
            new_name='variant',
        ),
        migrations.RenameField(
            model_name='salesproductvariant',
            old_name='external_variant',
            new_name='external_variant_title',
        ),
        migrations.RenameField(
            model_name='salesskuignore',
            old_name='external_variant',
            new_name='external_variant_title',
        ),
        migrations.RenameField(
            model_name='salesvariantmember',
            old_name='listing',
            new_name='variant',
        ),
        migrations.AddIndex(
            model_name='saleslinemodifier',
            index=models.Index(fields=['variant', 'sales_line'], name='forkluck_sa_variant_7205a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesvariantmember',
            constraint=models.UniqueConstraint(fields=('variant', 'product'), name='sales_variant_member_unique'),
        ),
    ]
