# Generated by Django 5.2.16 on 2026-09-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0026_kitchen_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='item_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['user', 'item_key'], name='forkluck_in_user_id_50306e_idx'),
        ),
    ]
