# Generated by Django 5.2.16 on 2026-09-02 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0032_recipe_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveWatchState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('page_token', models.CharField(blank=True, default='', max_length=256)),
                ('polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_file_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('web_view_link', models.URLField(blank=True, default='', max_length=500)),
                ('folder_path', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('imported', 'Imported'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], default='new', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('seen_at', models.DateTimeField()),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_files', to='forkluck.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['user', 'status'], name='forkluck_dr_user_id_b38c7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivefile',
            constraint=models.UniqueConstraint(fields=('user', 'drive_file_id'), name='drive_file_user_file_unique'),
        ),
    ]
