# Generated by Django 5.2.16 on 2026-09-02 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0038_backfill_supplier_item_pack_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefile',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('imported', 'Imported'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], default='new', max_length=16),
        ),
        migrations.CreateModel(
            name='DriveFileExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.JSONField(default=dict)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('escalated', models.BooleanField(default=False)),
                ('extracted_at', models.DateTimeField()),
                ('drive_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='forkluck.drivefile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
