# Generated by Django 5.2.16 on 2026-09-02 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0039_drive_file_extraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.JSONField(default=dict)),
                ('escalated', models.BooleanField(default=False)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='forkluck.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
