# Generated by Django 5.2.16 on 2026-09-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0042_invoice_document_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefileextraction',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivefileextraction',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivefileextraction',
            name='part',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drivefileextraction',
            name='region',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivefileextraction',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('imported', 'Imported'), ('skipped', 'Skipped')], default='ready', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='drive_file_part',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drivefileextraction',
            name='drive_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='forkluck.drivefile'),
        ),
        migrations.AddConstraint(
            model_name='drivefileextraction',
            constraint=models.UniqueConstraint(fields=('drive_file', 'part'), name='drive_file_extraction_part_unique'),
        ),
    ]
