# Generated by Django 5.2.16 on 2026-09-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0043_drive_file_extraction_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogingredient',
            name='is_seed',
        ),
    ]
