# Generated by Django 5.2.16 on 2026-09-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0044_remove_catalogingredient_is_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
