# Generated by Django 5.2.16 on 2026-09-04 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0045_invoice_document_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimoConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primo_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrimoMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=64)),
                ('parent_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('role', models.CharField(max_length=16)),
                ('parts', models.JSONField(default=list)),
                ('text', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='complete', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forkluck.primoconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='primoconversation',
            index=models.Index(fields=['user', 'is_archived', '-last_message_at', '-id'], name='forkluck_pr_user_id_0a7ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='primomessage',
            index=models.Index(fields=['conversation', 'created_at', 'id'], name='forkluck_pr_convers_0b5e04_idx'),
        ),
        migrations.AddConstraint(
            model_name='primomessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'message_id'), name='primo_message_unique'),
        ),
    ]
