# Generated by Django 5.2.16 on 2026-09-04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forkluck", "0046_primo_conversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientInvoicePrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_size",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=15, null=True
                    ),
                ),
                (
                    "purchase_unit",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_prices",
                        to="forkluck.ingredient",
                    ),
                ),
                (
                    "ingredient_import",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_prices",
                        to="forkluck.ingredientimport",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_prices",
                        to="forkluck.invoiceline",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_invoice_prices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-invoice_line__invoice__invoice_date",
                    "-created_at",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ingredientinvoiceprice",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "invoice_line"),
                name="ingredient_invoice_price_line_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientinvoiceprice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("purchase_size__isnull", True), ("purchase_unit", "")),
                    models.Q(
                        ("purchase_size__gt", 0),
                        models.Q(("purchase_unit", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ingredient_invoice_price_measure_pair",
            ),
        ),
    ]
