# Generated by Django 5.2.16 on 2026-09-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0049_fix_receipt_fingerprints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchcostsettings',
            options={'verbose_name_plural': 'bench cost settings'},
        ),
        migrations.AlterModelOptions(
            name='catalogimportbatch',
            options={'ordering': ['-observed_at', '-created_at'], 'verbose_name_plural': 'catalog import batches'},
        ),
        migrations.AlterModelOptions(
            name='catalogingredientalias',
            options={'ordering': ['normalized_text', 'text'], 'verbose_name_plural': 'catalog ingredient aliases'},
        ),
        migrations.AlterModelOptions(
            name='recipeequivalency',
            options={'verbose_name_plural': 'recipe equivalencies'},
        ),
        migrations.AlterModelOptions(
            name='recipelinematch',
            options={'ordering': ['normalized_text'], 'verbose_name_plural': 'recipe line matches'},
        ),
        migrations.AlterModelOptions(
            name='recipemedia',
            options={'ordering': ['position', 'created_at'], 'verbose_name_plural': 'recipe media'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-clock_in', '-created_at'], 'verbose_name_plural': 'time entries'},
        ),
    ]
