# Generated by Django 5.2.16 on 2026-09-05 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0051_invoice_ai_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_id', models.UUIDField()),
                ('rating', models.CharField(choices=[('up', 'Thumbs up'), ('down', 'Thumbs down')], max_length=4)),
                ('note', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=120)),
                ('extraction_model', models.CharField(max_length=64)),
                ('extraction', models.JSONField(blank=True, null=True)),
                ('original', models.JSONField(default=dict)),
                ('corrected', models.JSONField(default=dict)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Receipt feedback',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'submission_id'), name='receipt_feedback_user_submission_unique')],
            },
        ),
    ]
