# Generated by Django 5.2.16 on 2026-09-05 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0052_receipt_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='primomessage',
            name='feedback',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='primomessage',
            name='feedback_comment',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='PrimoAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.UUIDField()),
                ('document_key', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('coverage', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forkluck.primomessage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
