# Generated by Django 5.2.16 on 2026-09-05 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0053_primo_attachments_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackGrant',
            fields=[
                ('code_digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('credential_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('access_digest', models.CharField(max_length=64, null=True, unique=True)),
                ('access_expires_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
