# Generated by Django 5.2.16 on 2026-09-13 04:25

import django.db.models.deletion
import forkluck.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0057_fix_kitchen_ingredient_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edit_version', models.PositiveIntegerField(default=0)),
                ('public_id', models.CharField(default=forkluck.models.generate_saved_comparison_public_id, max_length=24, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('view', models.CharField(choices=[('formula', 'Formula'), ('spec', 'Spec sheet')], default='formula', max_length=12)),
                ('baseline_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedComparisonColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('pasted_title', models.CharField(blank=True, default='', max_length=120)),
                ('pasted_text', models.TextField(blank=True, default='')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='forkluck.savedcomparison')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_columns', to='forkluck.recipe')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='savedcomparison',
            index=models.Index(fields=['user', '-updated_at'], name='forkluck_sa_user_id_605a3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedcomparisoncolumn',
            constraint=models.UniqueConstraint(fields=('comparison', 'position'), name='saved_comparison_column_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='savedcomparisoncolumn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pasted_text', ''), ('recipe__isnull', False)), models.Q(('recipe__isnull', True), models.Q(('pasted_text', ''), _negated=True)), _connector='OR'), name='saved_comparison_column_recipe_or_pasted'),
        ),
    ]
