# Generated by Django 5.2.16 on 2026-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0058_saved_comparisons'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcomparison',
            name='overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedcomparison',
            name='percent_mode',
            field=models.CharField(choices=[('bakers', "Baker's %"), ('weight', 'Weight %')], default='bakers', max_length=8),
        ),
        migrations.AddField(
            model_name='savedcomparison',
            name='show_grams',
            field=models.BooleanField(default=False),
        ),
    ]
