# Generated by Django 5.2.16 on 2026-09-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkluck', '0060_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_attest_key_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('admin', 'Admin sign-in'), ('password_reset', 'Password reset'), ('device', 'Phone sign-in'), ('delete_account', 'Account deletion')], max_length=16),
        ),
    ]
